### ISSUE TITLE
一秒请求并发数500导致Freesql报错

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/FreeSql#1077]
#### 问题描述及重现步骤：
我进行压力测试,一秒500并发持续60秒,错误率达80%多
压力测试接口是一个查询接口
日志错误提示
2022/04/22 15:24:30 [Error] PrimaxMes.Extensions.AspNetCore.Filter.ApiErroFilter POST http://10.40.50.171:8101/api/Manage/FmBu/GetList
System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
   at FreeSql.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.GetAsync()
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivateAsync(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToOneAsync(CancellationToken cancellationToken)
   at Sso.Service.Webapi.Core.Filters.RoleCheckFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in /src/Src/Sso.Service.Webapi/Core/Filters/RoleCheckFilter.cs:line 60
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

#### 数据库的具体版本
数据库配置 Mssql2016 8C24G 10TB SSD 
连接字符串(敏感数据屏蔽) : server=0.0.0.0;Database=Database;User ID=saPassword=123;Encrypt=True;TrustServerCertificate=True;Max Pool Size = 512;Connect Timeout=60;

```C#
 var Fsql = new FreeSqlBuilder()
             .UseConnectionString(DataType.SqlServer, Section.Get<string>())
             .Build();
 services.AddSingleton(Fsql);
```

#### 安装的包
FreeSql.Provider.SqlServer 3.0.100

#### .net framework/. net core？ 及具体版本
NetCore 5.0

**Comment by 2881099** [comment]
FreeSql UseConnectionString 的机制是，一旦发生错误，则会将整个对象不可用，可以把它理解为断熔。

FreeSql UseConnectionFactory 的机制是，跟传统 ado.net 一样，你可以试下这种。

```c#
 var Fsql = new FreeSqlBuilder()
    .UseConnectionFactory(DataType.SqlServer, () => new SqlConnection(Section.Get<string>()))
    .Build();
 services.AddSingleton(Fsql);
```

**Comment by 2881099** [comment]
UseConnectionString 可以理解保护数据库服务器，一旦某条命令发生服务器错误，则禁止使用 IFreeSql 3-5 秒，因为接下来都会直接报错不会继续冲击数据库服务器（如一楼所描述那样）。

**Comment by bao2314483** [comment]
谢谢作者解答,让我有知道UseConnectionString和UseConnectionFactory的区别,
最终问题找到了
1. 测试工具设置错误
2. Oeclot配合Consul,设置了类型Consul,没有用PollConsul,导致大量请求错误在网关上,已经查明Consul默认连接数在200,过于保守
最终调整后,并发1W,持续30分钟,0%错误率,平均响应300ms+,非常满意
