### ISSUE TITLE
未实现函数表达式 Equals

### ISSUE THREAD

**Issue by responsibleboy** [dotnetcore/FreeSql#1150]
#### 问题描述及重现步骤：

新表，没有数据
dbcontext.Configs.Where(c => c.Status == ConfigStatus.Enabled && String.Equals(c.Env, env, StringComparison.OrdinalIgnoreCase));
ConfigStatus.Enabled 是枚举，env=“dev” 字符串

 未实现函数表达式 Equals(c.Env, value(AgileConfig.Server.Service.ConfigService+<>c__DisplayClass18_0).env, OrdinalIgnoreCase) 解析 
    at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionBinary(String oper, Expression leftExp, Expression rightExp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionWhereLambda(List`1 _tables, Expression exp, BaseDiyMemberExpression diymemexp, List`1 whereGlobalFilter, List`1 dbParams)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalWhere(Expression exp)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.WhereIf(Boolean condition, Expression`1 exp)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.Where(Expression`1 exp)
   at FreeSql.DbSet`1.Where(Expression`1 exp)

#### 数据库的具体版本
```
mysql8
```

#### 安装的包
```
3.2.661
```

#### .net framework/. net core？ 及具体版本
```
.net core 6
```

**Comment by 2881099** [comment]
dbcontext.Configs.Where(c => c.Status == ConfigStatus.Enabled && c.Env.ToLower() == env.To lower());
