### ISSUE TITLE
开启了UseGenerateCommandParameterWithLambda(true)之后，使用IEnumerable.Contain报错问题

### ISSUE THREAD

**Issue by zhaoyuehui123** [dotnetcore/FreeSql#1173]
#### 问题描述及重现步骤：
**开启了UseGenerateCommandParameterWithLambda(true)之后，使用IEnumerable.Contain报错**。

程序代码：
```
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    Db = new FreeSql.FreeSqlBuilder().UseConnectionFactory(FreeSql.DataType.SqlServer, () => new SqlConnection(Conn))
        //参数化
        .UseGenerateCommandParameterWithLambda(true)
        //build
        .Build<TestDbContext>();

    //convert to IEnumerable
    var arr = new[] { 1L, 2L, 3L }.Select(x => x);
    //or, such as
    //var arr = new HashSet<long> {1L, 2L, 3L};

    //execute
    await TestSqlIn(arr.Select(x => x));
}

/// <summary>
/// sql in
/// </summary>
Task TestSqlIn(IEnumerable<long> ids) => Db.Select<TestDb>().Where(x => ids.Contains(x.Id)).ToListAsync();
```
错误输出：
[https://static.qkj.com.cn/tempimg/111.png](url)
```
      System.Exception: Failed to convert parameter value from a SelectArrayIterator`2 to a Int64.
       ---> System.InvalidCastException: Failed to convert parameter value from a SelectArrayIterator`2 to a Int64.
       ---> System.InvalidCastException: Object must implement IConvertible.
         at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
         at Microsoft.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged
, Boolean allowStreaming)
         --- End of inner exception stack trace ---
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transa
ction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken c
ancellationToken)
         --- End of inner exception stack trace ---
         at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, String
Builder logtxt, Boolean isThrowException)
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transa
ction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken c
ancellationToken)
         at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivateAsync(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOthe
rInfo[] otherData, CancellationToken cancellationToken)
```

#### 数据库的具体版本
```
SqlServer 2016
```

#### 安装的包
```
FreeSql 3.2.664
FreeSql.Provider.SqlServer 3.2.664
```

#### .net framework/. net core？ 及具体版本
```
.net core 5
```

**Comment by 2881099** [comment]
这个问题与 #900 是同期问题，修东墙补西墙。目前算是彻底发现了问题。

**Comment by 2881099** [comment]
问题已修复，晚上跑单元测试后发布版本。
