### ISSUE TITLE
在postgresp数据库下，用Repository.insert 存储用Bcript加密的密码会报错

### ISSUE THREAD

**Issue by jesse996** [dotnetcore/FreeSql#1175]
#### 问题描述及重现步骤：
这个问题在mysql下不会出现，在postgres中会出现。使用BCrypt.Net.BCrypt.HashPassword加密后，
```
        var repo = _freeSql.GetRepository<SysUser>();
        var sysUser =await repo.InsertAsync(user);
```
会报错：
```
 System.Exception: Unexpected character encountered while parsing value: $. Path '', line 1, position 1
```
而下面却不会报错
```
_freeSql.Insert(user).ExecuteIdentity();
```

#### 数据库的具体版本
```
postgres14.3-1.pgdg110+1
```

#### 安装的包

![image](https://user-images.githubusercontent.com/20895372/176564937-6d154c4b-927e-410d-bda1-e1d11f4ac76f.png)

#### .net framework/. net core？ 及具体版本
```
net6
```

**Comment by 2881099** [comment]
实体类发一下，应该和 json 有关

**Comment by jesse996** [comment]
```
public record SysUser : BaseEntity
{
    public string Username { get; set; } = "";
    
    public string? Password { get; set; }
    
    [Column(IsIgnore = true)]
    public SysUserExt SysUserExt { get; set; } = null!;

    public string? Nickname { get; set; }

    [Column(IsNullable = false)] public string Phone { get; set; } = "";

    public string? Email { get; set; }

    /// <summary>
    /// 个性签名
    /// </summary>
    public string? Motto { get; set; }
    
    /// <summary>
    /// 头像
    /// </summary>
    public string? Avatar { get; set; }
    
}
```
```
public record BaseEntity
{
    [Column(IsIdentity = true)] public int Id { get; set; }

    // [Column(ServerTime = DateTimeKind.Local, CanUpdate = false, DbType = "datetime not null default now()")]
    [Column(ServerTime = DateTimeKind.Local, CanUpdate = false)]
    public DateTime CreateTime { get; set; }

    // [Column(ServerTime = DateTimeKind.Local, DbType = "datetime not null default now()")]
    [Column(ServerTime = DateTimeKind.Local)]
    public DateTime UpdateTime { get; set; }

    // [Column(DbType = "bool not null default false")]
    public bool IsDeleted { get; set; } = false;

    // [Column(DbType = "int not null default 0")]
    public int Version { get; set; } = 0;
}
```

**Comment by 2881099** [comment]
~[Column(IsIgnore = true)]~
    public SysUserExt SysUserExt { get; set; } = null!;

导致属性情况下，这个 IsIgnore 不需要设置的

**Comment by jesse996** [comment]
不明白哪里有问题
![image](https://user-images.githubusercontent.com/20895372/176572801-0aac7998-5487-4109-995e-e702f2357122.png)
![image](https://user-images.githubusercontent.com/20895372/176572819-adabc921-ddb4-4579-aacc-b691aa918063.png)
![image](https://user-images.githubusercontent.com/20895372/176572840-c3f4efe8-d72e-476c-91ba-b42893e20822.png)
![image](https://user-images.githubusercontent.com/20895372/176572869-fbf405fd-66e4-4b84-908a-132abe11c375.png)

**Comment by 2881099** [comment]
1、打印 SQL

.UseMonitorCommand(cmd => Trace.WriteLine(cmd.CommandText))

2、监视元数据

var tb = fsql.CodeFirst.GetTableByEntity(typeof(SysUser))

3、打印错误信息及堆栈

**Comment by jesse996** [comment]
![image](https://user-images.githubusercontent.com/20895372/176574046-e4cd3f08-cbae-4f3a-a14c-653ed4de0df1.png)
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: Unexpected character encountered while parsing value: j. Path '', line 1, position 1.
       ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: j. Path '', line 1, position 1.
         at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
         at Newtonsoft.Json.JsonTextReader.ReadAsString()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at lambda_method6(Closure , Type , Int32[] , DbDataReader , Int32 , CommonUtils )
         at FreeSql.Internal.Utils.ExecuteArrayRowReadClassOrTuple(String flagStr, Type typeOrg, Int32[] indexes, DbDataReader row, Int32 dataIndex, CommonUtils _commonUtils)
         at lambda_method4(Closure , IFreeSql , DbDataReader )
         at FreeSql.Internal.CommonProvider.Select0Provider`2.<>c__DisplayClass62_0.<ToListAfPrivate>b__0(FetchCallbackArgs`1 fetch)
         at FreeSql.Internal.CommonProvider.AdoProvider.<>c__DisplayClass79_0.<ExecuteReader>b__0(FetchCallbackArgs`1 fetch, Int32 result)
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, Co
mmandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
         --- End of inner exception stack trace ---
         at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, Co
mmandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReader(DbConnection connection, DbTransaction transaction, Action`1 fetchHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, D
bParameter[] cmdParms)
         at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivate(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData)
         at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListPrivate(GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData)
         at FreeSql.Internal.CommonProvider.Select0Provider`2.ToList(Boolean includeNestedMembers)
         at FreeSql.Internal.CommonProvider.Select1Provider`1.ToList(Boolean includeNestedMembers)
         at FreeSql.Internal.CommonProvider.Select0Provider`2.ToList()
         at runApi.Controllers.NftController.List() in C:\Users\jesse\RiderProjects\runApi\Controllers\NftController.cs:line 52
         at lambda_method2(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] argu
ments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isC
ompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by 2881099** [comment]
sys_nft_user
sys_user

这两个类发一下

**Comment by 2881099** [comment]
```c#
var cols1 = fsql.CodeFirst.GetTableByEntity(typeof(sys_nft_user)).ColumnsByCs
    .Where(a => !new[] { typeof(string), typeof(int), typeof(DateTime), typeof(long) }.Contains(a.Value.Attribute.MapType))
    .ToArray();

var cols1 = fsql.CodeFirst.GetTableByEntity(typeof(sys_user)).ColumnsByCs
    .Where(a => !new[] { typeof(string), typeof(int), typeof(DateTime), typeof(long) }.Contains(a.Value.Attribute.MapType))
    .ToArray();
```

监视他们，发出来

**Comment by jesse996** [comment]
```
public class SysNftUser : BaseEntity
{
    public string? TokenId { get; set; }
    
    public int NftClassId { get; set; }
    [Navigate(nameof(NftClassId))] public SysNftClass NftClass { get; set; } = null!;

    public int UserId { get; set; }
    
    [Navigate(nameof(UserId))] 
    public SysUser User { get; set; } = null!;

  
}
```
```
public class SysUser : BaseEntity
{
    public string Username { get; set; } = "";
    
    public string? Password { get; set; }
    
    // public SysUserExt SysUserExt { get; set; } = null!;

    public string? Nickname { get; set; }

    [Column(IsNullable = false)] public string Phone { get; set; } = "";

    public string? Email { get; set; }
    
    public string? Motto { get; set; }
    
    public string? Avatar { get; set; }
    
}
```

**Comment by jesse996** [comment]
![image](https://user-images.githubusercontent.com/20895372/176575097-b6752dfa-c2f2-4e3e-a2a2-80edd65f91fa.png)


> ```cs
> var cols1 = fsql.CodeFirst.GetTableByEntity(typeof(sys_nft_user)).ColumnsByCs
>     .Where(a => !new[] { typeof(string), typeof(int), typeof(DateTime), typeof(long) }.Contains(a.Value.Attribute.MapType))
>     .ToArray();
> 
> var cols1 = fsql.CodeFirst.GetTableByEntity(typeof(sys_user)).ColumnsByCs
>     .Where(a => !new[] { typeof(string), typeof(int), typeof(DateTime), typeof(long) }.Contains(a.Value.Attribute.MapType))
>     .ToArray();
> ```

我加上这2个就没报错了，不加又报错了

**Comment by 2881099** [comment]
> ![image](https://user-images.githubusercontent.com/20895372/176575097-b6752dfa-c2f2-4e3e-a2a2-80edd65f91fa.png)
> 
> > ```cs
> > var cols1 = fsql.CodeFirst.GetTableByEntity(typeof(sys_nft_user)).ColumnsByCs
> >     .Where(a => !new[] { typeof(string), typeof(int), typeof(DateTime), typeof(long) }.Contains(a.Value.Attribute.MapType))
> >     .ToArray();
> > 
> > var cols1 = fsql.CodeFirst.GetTableByEntity(typeof(sys_user)).ColumnsByCs
> >     .Where(a => !new[] { typeof(string), typeof(int), typeof(DateTime), typeof(long) }.Contains(a.Value.Attribute.MapType))
> >     .ToArray();
> > ```
> 
> 我加上这2个就没报错了，不加又报错了

是监视，不是打印，打印出来就是一个类型而已看不明白

**Comment by jesse996** [comment]
怎么监视呀，我不太懂

**Comment by 2881099** [comment]
vs 调试环境，监视器

或者你就打印吧

Console.WriteLine(string.Join(", ", cols1.Select(a => a.Value.CsName).ToArray()));
Console.WriteLine(string.Join(", ", cols2.Select(a => a.Value.CsName).ToArray()));

**Comment by 2881099** [comment]
你用了 JsonMap 吗

**Comment by jesse996** [comment]
用了的

**Comment by jesse996** [comment]
```
public class SysNftClass : BaseEntity
{
    [Column(IsNullable = false)] public string Image { get; set; } = null!;
    [Column(IsNullable = false)] public string Name { get; set; } = null!;

    /// <summary>
    /// 发行数量
    /// </summary>
    public int Supply { get; set; }

    /// <summary>
    /// 创造者
    /// </summary>
    public int UserId { get; set; }
    [Navigate(nameof(UserId))]
    public SysUser User { get; set; } = null!;
    
    [Column(StringLength =-1)]
    public string? Empower { get; set; }
    
    [JsonMap]
    public string EmpowerImages { get; set; }
    
    [Column(StringLength =-1)]
    public string? Description { get; set; }
    
    public long InitialPrice { get; set; }
}
```
这个类用了

**Comment by jesse996** [comment]
果然去掉jsonmap就没报错了，是用不了jsonmap吗？

**Comment by 2881099** [comment]
JsonMap 读取的时候会反序列化，因为数据库内不是有效的 json 格式就会报错。

JsonMap 标记的类型，不能是实体类，会有冲突。

**Comment by 2881099** [comment]
而且 string 更加没有必要加 JsonMap

**Comment by jesse996** [comment]
哦哦，感谢，我忘了改回去了，之前是用的 List<string>
