### ISSUE TITLE
使用FreeSql，出现System.InvalidOperationException: The connection does not support MultipleActiveResultSets

### ISSUE THREAD

**Issue by km93522719** [dotnetcore/FreeSql#1227]
#### 问题描述及重现步骤：
麻烦帮忙解释一下为什么使用FreeSql会出现The connection does not support MultipleActiveResultSets.
异常信息：[【InnerException】：System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)。【Exception】：The connection does not support MultipleActiveResultSets.]

框架：. net core 6.0

**Comment by 2881099** [comment]
连接串：MultipleActiveResultSets=true

**Comment by km93522719** [comment]
已经添加上MultipleActiveResultSets=true了，但是没有效果

**Comment by 2881099** [comment]
那就要看服务器是不是云服务器，也许服务器不支持。

**Comment by 2881099** [comment]
FreeSql.Provider.SqlServerForSystem.dll

替换成这个试下

**Comment by km93522719** [comment]
> FreeSql.Provider.SqlServerForSystem.dll
> 
> 替换成这个试下

使用这个，是支持云服务器的吗？

**Comment by 2881099** [comment]
这个是使用 System.Data.SqlClient，要测试一下

**Comment by km93522719** [comment]
> 这个是使用 System.Data.SqlClient，要测试一下

我们这边的数据库是云服务器的，现在换成FreeSql.Provider.SqlServerForSystem.dll，已经不出现这个问题了，谢谢
