### ISSUE TITLE
pgsql JsonMap 自定义Dictionary查询数据报错

### ISSUE THREAD

**Issue by zenghui** [dotnetcore/FreeSql#141]
```
    public class DecimalDict : Dictionary<string, decimal> {
    }

    public class Class1 {
        [Column(IsPrimary = true, IsIdentity = true, IsNullable = false)]
        public long ID { get; set; }


        [JsonMap]
        [Column(DbType = "jsonb", Name = "avg")]
        public DecimalDict Avg { get; set; } 
    }
```

Unhandled exception. System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at FreeSql.Internal.Utils.GetTableByEntity(Type entity, CommonUtils common)
   at FreeSql.Internal.CommonUtils.GetTableByEntity(Type entity)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.<GetAllFieldExpressionTreeLevel2>b__71_1(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.GetAllFieldExpressionTreeLevel2()
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToList(Boolean includeNestedMembers)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.ToList(Boolean includeNestedMembers)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToOne()
   at FreeSql.Internal.CommonProvider.Select0Provider`2.First()
   at freepgsql.Program.Do4() in C:\Users\dell\source\repos\freepgsql\Program.cs:line 120
   at freepgsql.Program.Main(String[] args) in C:\Users\dell\source\repos\freepgsql\Program.cs:line 56

**Comment by 2881099** [comment]
pgsql 下，可以直接用 Dictionary<string, string>，不必要用 JsonMap 

https://github.com/2881099/FreeSql/wiki/%e7%b1%bb%e5%9e%8b%e6%98%a0%e5%b0%84
这里有类型映射目录

**Comment by zenghui** [comment]
只能直接用Dictionary<>吗？不能封装下吗

**Comment by 2881099** [comment]
不能，这个对应hstore类型

**Comment by zenghui** [comment]
报错好像是因为把DecimalDict 当作数据库Table来处理了

**Comment by 2881099** [comment]
是的，改成Dict\<string, string>
