### ISSUE TITLE
并发报 Connect Timeout expired

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1440]
freesql 3.2.687
以下是服务端代码。
    [Table(Name = "goods")]
    public class Goods
    {
        /// <summary>
        /// ID
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; } = "";

        /// <summary>
        /// 库存
        /// </summary>
        public int Stock { get; set; }

        /// <summary>
        /// 乐观锁 即是在数据记录版本号
        /// </summary>
        [Column(IsVersion = true)]
        public int Revision { get; set; }
    }

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var Fsql = new FreeSqlBuilder()
    .UseConnectionFactory(DataType.MySql, () => new MySqlConnection("Data Source=localhost;Port=3306;User ID=root;Password=sa_123; Initial Catalog=testbb;Charset=utf8; SslMode=none;Min pool size=1;Connect Timeout =25") )
              //  .UseConnectionString(FreeSql.DataType.MySql, @"Data Source=localhost;Port=3306;User ID=root;Password=sa_123; Initial Catalog=testbb;Charset=utf8; SslMode=none;Min pool size=1")
                .UseAutoSyncStructure(true)
                .UseMonitorCommand(cmd => Trace.WriteLine(cmd.CommandText))
                .UseNoneCommandParameter(true)
                .Build();

Fsql.Aop.TraceBefore += (_, e) => Trace.WriteLine($"----TraceBefore---{e.Identifier} {e.Operation}");
Fsql.Aop.TraceAfter += (_, e) => Trace.WriteLine($"----TraceAfter---{e.Identifier} {e.Operation} {e.Remark} {e.Exception?.Message} {e.ElapsedMilliseconds}ms\r\n");

builder.Services.AddSingleton<IFreeSql>(Fsql);
builder.Services.AddScoped<UnitOfWorkManager>();

//批量注入
foreach (var repo in typeof(Program).Assembly.GetTypes()
    .Where(a => a.IsAbstract == false && typeof(IBaseRepository).IsAssignableFrom(a)))
    builder.Services.AddScoped(repo);

Fsql.CodeFirst.SyncStructure(typeof(Goods));
//Fsql.Insert<Goods>(new Goods
//{
//    Id = 1,
//    Name = "test",
//    Stock = 10,
//}).ExecuteAffrows();
var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

[ApiController]
    [Route("[controller]")]
    public class GoodsController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<GoodsController> _logger;
        private readonly IFreeSql _freeSql;
        public GoodsController(ILogger<GoodsController> logger, IFreeSql freeSql)
        {
            _logger = logger;
            _freeSql = freeSql;
        }

 

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<int> Test()
        {
            var goods = await _freeSql.Select<Goods>().Where(x => x.Id == 1).ToOneAsync();
            if (goods.Stock > 0)
            {
                await Task.Delay(200);
                goods.Stock = goods.Stock - 1;
                await _freeSql.Update<Goods>().Where(x => x.Id == 1).SetSource(goods).ExecuteAffrowsAsync();
               
            }
            return 1;
        }
    }
以上是asp.net core 代码，下面是并发测试
Parallel.For(1, 100, async (a) =>
{
    try
    {
        await Testb();
        Console.WriteLine($"第{a}次");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"第{a}次失败：{ex.Message}");

    }

});
Console.ReadLine();
 
async Task Testb()
{
    using (var client = new HttpClient())
    {
        var a = await client.GetStringAsync("https://localhost:7052/Goods");

        Console.WriteLine($"a:{a}");

    }
}
报以下错误
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: Connect Timeout expired.
       ---> MySqlConnector.MySqlException (0x80004005): Connect Timeout expired.
       ---> MySqlConnector.MySqlException (0x80004005): Connect Timeout expired.
         at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1033
         at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 422
         at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
         at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
         at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
         at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 911
         at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 933
         at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 405
         at FreeSql.Internal.CommonProvider.DbConnectionPool.GetAsync()
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQueryAsync(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, Func`2 cmdAfterHandler, DbParameter[] cmdParms, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
请老大帮看看。

**Comment by luoyunchong** [comment]
UseConnectionString 呢

**Comment by sukney** [comment]
ThreadPool.SetMinThreads(1000, 1000);  开头设置这个就不报了。
