### ISSUE TITLE
在使用日期表达式函数 (a.CreatedTime.BetweenEnd) 的时候报错，System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.

### ISSUE THREAD

**Issue by Deali-Axy** [dotnetcore/FreeSql#1499]
#### 问题描述及重现代码：

使用该查询代码，查询2023年1月到4月之间的数据时报时间超出范围的错误

```c#
var instRepo = freeSql.GetRepository<ProcInstance>();
var list = await instRepo.Where(a =>
            a.ProcDefName != null
            && a.CreatedTime.BetweenEnd(new DateTime(2023, 1, 1), new DateTime(2023, 4, 1))
    )
    .ToListAsync();
```

报错信息如下：

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at FreeSqlGlobalExtensions.CreateInstanceGetDefaultValue(Type that)
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionBinary(String oper, Expression leftExp, Expression rightExp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionWhereLambda(List`1 _tables, Func`3 _tableRule, Expression exp, BaseDiyMemberExpression diymemexp, List`1 whereG
lobalFilter, List`1 dbParams)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalWhere(Expression exp)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.WhereIf(Boolean condition, Expression`1 exp)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.Where(Expression`1 exp)
   at FreeSql.BaseRepository`1.Where(Expression`1 exp)
   at Program.<Main>$(String[] args) in ~/Code/DataProc/Program.cs:line 40
   at Program.<Main>(String[] args)
```

模型定义

```c#
public class ProcInstance {
    [Column(IsPrimary = true)]
    public string Id { get; set; }
    public string? ProcDefName { get; set; }
    public DateTime CreatedTime { get; set; } = DateTime.Now;
    public DateTime ModifiedTime { get; set; } = DateTime.Now;
    public bool IsDeleted { get; set; } = false;
}
```

#### 数据库版本

Oracle 11.2.0.4.0

#### 安装的Nuget包

- FreeSql 3.2.693
- FreeSql.Provider.Oracle 3.2.693
- FreeSql.Repository 3.2.693

#### .net framework/. net core？ 及具体版本

```bash
$ dotnet --version
6.0.404
```

**Comment by 2881099** [comment]
用 DateTime.Parse()

**Comment by Deali-Axy** [comment]
> 用 DateTime.Parse()

感谢解答，`DateTime.Parse()` 可以运行。

但我还有个疑问，根据查到的资料和各种讨论，`new DateTime()` 和 `DateTime.Parse()` 这两种方法没有很大的区别，且 `new DateTime()` 更方便使用，不需要考虑 日期的culture格式问题，为什么我使用 `new DateTime()` 会报错呢？

**Comment by 2881099** [comment]
不一样，表达式树是解析的过程。当前没有处理 new DateTime.. 的解析

**Comment by 2881099** [comment]
lambda 表达式树，只是数据结构，虽然看起来和 c# 委托一样，它最终是递归结构解析产生 SQL，而不是直接运行委托。

**Comment by Deali-Axy** [comment]
理解了，感谢大佬解答~
