### ISSUE TITLE
在GroupBy之后的WithTempQuery、ToList自定义函数解析报错

### ISSUE THREAD

**Issue by sungyow** [dotnetcore/FreeSql#1502]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

#### 问题描述及重现代码：
自定义函数解析在以下函数中报错
```
ISelect<TDto> WithTempQuery<TDto>(Expression<Func<ISelectGroupingAggregate<TKey, TValue>, TDto>> selector)
List<TReturn> ToList<TReturn>(Expression<Func<ISelectGroupingAggregate<TKey, TValue>, TReturn>> select)
```
异常信息
```
Message	Object reference not set to an instance of an object.
StackTrace	   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 1822
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 1028
   at FreeSql.Internal.CommonExpression.ReadAnonymousField(List`1 _tables, Func`3 _tableRule, StringBuilder field, ReadAnonymousTypeInfo parent, Int32& index, Expression exp, Select0Provider select, BaseDiyMemberExpression diymemexp, List`1 whereGlobalFilter, List`1 findIncludeMany, List`1 findSubSelectMany, Boolean isAllDtoMap) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 138
   at FreeSql.Internal.CommonExpression.ReadAnonymousField(List`1 _tables, Func`3 _tableRule, StringBuilder field, ReadAnonymousTypeInfo parent, Int32& index, Expression exp, Select0Provider select, BaseDiyMemberExpression diymemexp, List`1 whereGlobalFilter, List`1 findIncludeMany, List`1 findSubSelectMany, Boolean isAllDtoMap) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 447
   at FreeSql.Internal.CommonExpression.ReadAnonymousField(List`1 _tables, Func`3 _tableRule, StringBuilder field, ReadAnonymousTypeInfo parent, Int32& index, Expression exp, Select0Provider select, BaseDiyMemberExpression diymemexp, List`1 whereGlobalFilter, List`1 findIncludeMany, List`1 findSubSelectMany, Boolean isAllDtoMap) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 87
   at FreeSql.Internal.CommonProvider.SelectGroupingProvider.InternalToList(Expression select, Type elementType) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\SelectGroupingProvider.cs:line 163
   at FreeSql.Internal.CommonProvider.SelectGroupingProvider`2.ToList[TReturn](Expression`1 select) in C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\SelectGroupingProvider.cs:line 336
   at UserQuery.Main() in C:\Users\ZXL\AppData\Local\Temp\LINQPad7\_outlgnnv\kuqhna\LINQPadQuery:line 29
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
```
linqpad重现脚本
```c#
void Main()
{
	var connectionString = "Data Source=.; Port=3306; User ID=root; Password=root; Initial Catalog=DB; Charset=utf8; SslMode=none; Min pool size=1; allowuservariables=True";
	var freesql = new FreeSqlBuilder()
			.UseConnectionString(DataType.MySql, connectionString)
			.UseMonitorCommand(cmd => $"Sql：{cmd.CommandText}".Dump())
			.Build();

	//Normal
	freesql.Select<Achievement>()
			 .Where(e => e.Property("项目执行情况") == "结题")
			 .WithTempQuery(e => new
			 {
				 Test = e.Property("项目级别"),
			 })
	.ToSql()
	.Dump();
	//Normal
	freesql.Select<Achievement>()
			 .Where(e => e.Property("项目执行情况") == "结题")
			 .WithTempQuery(e => new
			 {
				 Test = decimal.Parse(e.Property("批准经费总额（万元）")),
			 })
	.ToSql()
	.Dump();

	//Error
	freesql.Select<Achievement>()
			 .Where(e => e.Property("项目执行情况") == "结题")
			 .GroupBy(e => new { ProjectLevel = e.Property("项目级别") })
			 .ToList(e => new
			 {
				 e.Key.ProjectLevel,
				 Test = e.Value.Property("批准经费总额（万元）"),
			 });
	freesql.Select<Achievement>()
			 .Where(e => e.Property("项目执行情况") == "结题")
			 .GroupBy(e => new { ProjectLevel = e.Property("项目级别") })
			 .WithTempQuery(e => new
			 {
				 e.Key.ProjectLevel,
				 Test = e.Value.Property("批准经费总额（万元）"),
			 })
	.ToSql()
	.Dump();
}
[ExpressionCall]
public static class AchievementExpressionExtension
{
	static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();
	public static string Property(this Achievement achievement, string fieldName)
	{
		var ctx = context.Value;
		var prefix = ctx.ParsedContent["achievement"];
		prefix = prefix.Substring(0, prefix.IndexOf('.') + 1);
		ctx.Result = prefix + $"`{fieldName}`";
		return default;
	}
}
public class Achievement
{

}
```

#### 安装的Nuget包
	<PackageReference Include="FreeSql" Version="3.2.693" />
	<PackageReference Include="FreeSql.Provider.MySqlConnector" Version="3.2.693" />
	<PackageReference Include="FreeSql.Extensions.LazyLoading" Version="3.2.693" />
	<PackageReference Include="FreeSql.DbContext" Version="3.2.693" />

#### .net framework/. net core？ 及具体版本
.Net6

**Comment by 2881099** [comment]
长见识了，居然可以这样来动态操作。

**Comment by 2881099** [comment]
暂时不好处理，可以迂回解决。

```csharp
var isusers01 = fsql.Select<Achievement>()
    .Where(e => e.Property("项目执行情况") == "结题")
    .GroupBy(e => new { ProjectLevel = e.Property("项目级别") })
    .ToSql(e => new
    {
        e.Key.ProjectLevel,
        Test = e.Value.Group.Property("批准经费总额（万元）"),
    });
isusers01 = fsql.Select<Achievement>()
            .Where(e => e.Property("项目执行情况") == "结题")
            .GroupBy(e => new { ProjectLevel = e.Property("项目级别") })
            .WithTempQuery(e => new
            {
                e.Key.ProjectLevel,
                Test = e.Value.Group.Property("批准经费总额（万元）"),
            })
.ToSql();


    [Table(DisableSyncStructure = true)]
    public class Achievement
    {
        [Column(MapType = typeof(string))]
        public Achievement Group { get; set; }
    }
```

**Comment by 2881099** [comment]
```c#
//v3.2.694 emit 动态创建实体类型
Type type = fsql.CodeFirst.DynamicEntity("user", new TableAttribute { Name = "t_user" })
    .Property("id", typeof(int), new ColumnAttribute { IsIdentity = true, IsPrimary = rue })
    .Property("username", typeof(string), new ColumnAttribute { StringLength = 32 })
    .Build();

//如果有必要，请将 type 缓存起来

Dictionary<string, object> dict = new Dictionary<string, object>();
dict["id"] = 1;
dict["username"] = "xxx";

//将字典转化成 type 对应的 object
object obj = FreeSql.Internal.DynamicCompileBuilder.CreateObjectByTypeByCodeFirst(fsql, type, dict);

//插入
fsql.Insert<object>().AsType(type).AppendData(obj).ExecuteAffrows();
//更新
fsql.Update<object>().AsType(type).SetSource(obj).ExecuteAffrows();
//插入或更新
fsql.InsertOrUpdate<object>().AsType(type).SetSource(obj).ExecuteAffrows();
//删除
fsql.Delete<object>().AsType(type).WhereDynamic(obj).ExecuteAffrows();
//查询
List<object> objs = fsql.Select<object>().AsType(type).ToList();
```

**Comment by sungyow** [comment]
迂回解决可以，也可以先select再group by
``` C#
freesql.Select<Achievement>()
	.WithTempQuery(e => new{All=e,ProjectLevel = e.Property("项目级别"), Test= e.Property("批准经费总额（万元）")})
	.Where(e => e.All.Property("项目执行情况") == "结题")
	.GroupBy(e => new { e.ProjectLevel  })
	.WithTempQuery(e => new
	{
		e.Key.ProjectLevel,
		e.Value.Test,
	})
	.ToSql()
	.Dump();
```
