### ISSUE TITLE
懒加载动态编译报错

### ISSUE THREAD

**Issue by sungyow** [dotnetcore/FreeSql#1506]
#### 问题描述及重现代码：
初次访问懒加载代码时有一定概率会出现此问题(不了解怎样触发的异常，不是每次都会出现)，再次访问时应该不会重新编译？
导致导航属性失效，成为了普通属性，而用到导航属性的部分都会异常(取值取不到的空异常、查询时通过导航属性获取字段值生成的Join Sql的ON部分为空)，只能重启程序碰运气

```
An unhandled exception has occurred while executing the request.
System.Exception: FreeSql: RSM.Domain.UserPersonal Compilation error: Exception has been thrown by the target of an invocation.\r\n\r\nusing System;
using FreeSql.DataAnnotations;
using System.Collections.Generic;
using System.Linq;

public class FreeSqlLazyEntity__RSM_Domain_UserPersonal : RSM.Domain.UserPersonal {
        private IFreeSql __fsql_orm__ { get; set; }

        private bool __lazy__User = false;
        public  override RSM.Domain.SystemUser User {
                 get {
                        if (base.User == null && __lazy__User == false) {
                                var loc3 = __fsql_orm__.Select<RSM.Domain.SystemUser>().Where(a => a.Id == this.UserId).ToOne();
                                base.User = loc3;
                                __lazy__User = true;
                        }
                        return base.User;
                }
                 set {
                        base.User = value;
                        if (value != null) __lazy__User = true;
                }
        }
}

   at FreeSql.Internal.Utils.GetTableByEntity(Type entity, CommonUtils common)
   at FreeSql.Internal.Utils.AddTableRef(CommonUtils common, TableInfo trytb, PropertyInfo pnv, Boolean isLazy, NativeTuple`5 vp, StringBuilder cscode)
   at FreeSql.Internal.Utils.GetTableByEntity(Type entity, CommonUtils common)
   at FreeSql.Internal.CommonUtils.GetTableByEntity(Type entity)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.GetTableByEntity(Type type)
   at FreeSql.RepositoryDbContext.Set(Type entityType)
   at FreeSql.DbContext.Set[TEntity]()
   at FreeSql.BaseRepository`1.get__dbset()
   at FreeSql.BaseRepository`2.Get(TKey id)
   at RSM.Service.UserService.GetEntityById(Int64 id)
```

```c#
[Table(Name = nameof(SystemUser))]
public class SystemUser : IdentityUser<long>
{
    public string Name { set; get; }
    public long UnitId { get; set; }
    public long DeptId { get; set; }
    public long? CreateBy { set; get; }
    public DateTime? CreateTime { set; get; }
    public long? UpdateBy { set; get; }
    public DateTime? UpdateTime { set; get; }
    public bool IsDelete { set; get; }
    public DateTime? DeleteTime { set; get; }
    public DateTime? Period { get; set; }
    public bool IsDisabled { set; get; }
    [Navigate(nameof(Id), TempPrimary = nameof(UserPersonal.UserId)), JsonIgnore]
    public virtual UserPersonal UserPersonal { set; get; }
}

[Table(Name = nameof(UserPersonal))]
public class UserPersonal
{
    [Column(IsPrimary = true)]
    public long UserId { get; set; }
    public string Officer { get; set; }
    public string Education { get; set; }
    [Navigate(nameof(UserId))]
    public virtual SystemUser User { get; set; }
}
```
#### 数据库版本
mysql 8

#### 安装的Nuget包
		<PackageReference Include="FreeSql.Extensions.JsonMap" Version="3.2.693" />
		<PackageReference Include="FreeSql" Version="3.2.693" />
		<PackageReference Include="FreeSql.Extensions.LazyLoading" Version="3.2.693" />
		<PackageReference Include="FreeSql.Provider.MySqlConnector" Version="3.2.693" />
		<PackageReference Include="FreeSql.Repository" Version="3.2.693" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.2.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.2.0" />

#### .net framework/. net core？ 及具体版本
.Net6

**Comment by 2881099** [comment]
把报错下面的重写类代码，复制到项目内编译试试

**Comment by sungyow** [comment]
直接粘到项目里不行，还需要修改什么吗

**Comment by 2881099** [comment]
不行，具体什么提示

**Comment by sungyow** [comment]
还是会报一样的错误，粘贴进去的代码没有被访问到吧

**Comment by 2881099** [comment]
代码复制到项目内，具体错误就是编译错误了，发出来

**Comment by sungyow** [comment]
额 编译是通过的 代码没有问题，只是运行时会报一样的错误...

**Comment by 2881099** [comment]
需要下载源码 freesql.extensions.lazyloading 断点调试。

**Comment by sungyow** [comment]
引入源码进行调试出现以下错误，项目同时有用到DotNetCore.Natasha.CSharp进行一些动态编译操作，看起来是这部分引起的，里面提到的路径是动态生成的dll，为何会引起争用，能帮忙分析下吗
```
System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'C:\project\NetCore\rsm\src\RSM.Web\bin\Debug\net6.0\DynamicLibraryFolders\DynamicAchievement.0BED9E520FFAFE468355FF955DD87F94\RSM.Domain.Dynamic.dll' because it is being used by another process.
  Source=System.Private.CoreLib
  StackTrace:
   在 Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   在 Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   在 System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   在 Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
   在 Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   在 Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver.<>c.<.ctor>b__11_0(String path, MetadataReferenceProperties properties)
   在 Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver.CreateResolvedMissingReference(String fullPath)
   在 Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver.ResolveMissingAssembly(MetadataReference definition, AssemblyIdentity referenceIdentity)
   在 Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveAndBindMissingAssemblies(TCompilation compilation, ImmutableArray`1 explicitAssemblies, ImmutableArray`1 explicitModules, ImmutableArray`1 explicitReferences, ImmutableArray`1 explicitReferenceMap, MetadataReferenceResolver resolver, MetadataImportOptions importOptions, Boolean supersedeLowerVersions, ArrayBuilder`1 referenceBindings, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& allAssemblies, ImmutableArray`1& metadataReferences, ImmutableArray`1& resolvedReferences, ImmutableDictionary`2& implicitReferenceResolutions, DiagnosticBag resolutionDiagnostics)
   在 Microsoft.CodeAnalysis.CommonReferenceManager`2.Bind(TCompilation compilation, ImmutableArray`1 explicitAssemblies, ImmutableArray`1 explicitModules, ImmutableArray`1 explicitReferences, ImmutableArray`1 explicitReferenceMap, MetadataReferenceResolver resolverOpt, MetadataImportOptions importOptions, Boolean supersedeLowerVersions, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& allAssemblies, ImmutableArray`1& implicitlyResolvedReferences, ImmutableArray`1& implicitlyResolvedReferenceMap, ImmutableDictionary`2& implicitReferenceResolutions, DiagnosticBag resolutionDiagnostics, Boolean& hasCircularReference, Int32& corLibraryIndex)
   在 Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   在 Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   在 Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions)
   在 Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions, DiagnosticBag diagnostics)
   在 Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CreateModuleBuilder(EmitOptions emitOptions, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, IEnumerable`1 manifestResources, CompilationTestData testData, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   在 Microsoft.CodeAnalysis.Compilation.CheckOptionsAndCreateModuleBuilder(DiagnosticBag diagnostics, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   在 Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, RebuildData rebuildData, CompilationTestData testData, CancellationToken cancellationToken)
   在 Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, RebuildData rebuildData, CancellationToken cancellationToken)
   在 CSScriptLib.RoslynEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   在 CSScriptLib.RoslynEvaluator.CompileCode(String scriptText)
   在 FreeSql.Extensions.LazyLoading.LazyLoadingComplier.CompileCode(String cscode) 在 C:\project\NetCore\research-management-core\FreeSql.Extensions.LazyLoading\LazyLoadingComplier.cs 中: 第 24 行

```

**Comment by sungyow** [comment]
现在我直接引用源码了，在FreeSql.Extensions.LazyLoading.LazyLoadingComplier.CompileCode里套了层循环try..catch，暂时这么处理的

**Comment by 2881099** [comment]
可以自己新建一个

**Comment by sungyow** [comment]
改了之后还是会有占用问题，但做过容错后倒也能解决。
就是部署在iis长时间运行之后不知原因的懒加载失效，现在是没有ERROR，懒加载部分直接失效了，造成页面异常，往往重启程序就解决了，可能因为本地没有这么久的跑过还没能复现过，还会有什么问题呢？
下面附上改写的代码，为了排查加了些日志，排查日志发现Assembly已经加载完成，但在之后的时间点的日志中发生了异常，正是访问导航属性数据的部分。
```csharp
using Microsoft.Extensions.Logging;
using System.Collections.Concurrent;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace FreeSql.Extensions.LazyLoading;

public class LazyLoadingComplier
{
    public const string DomainName = "FreeSql.Extensions.LazyLoading";
    static NatashaReferenceDomain Domain { set; get; } = DomainManagement.Create(DomainName);
    internal static ConcurrentDictionary<string, Assembly> Cache = new();
    internal static ILogger<LazyLoadingComplier> logger;
    public static Assembly CompileCode(string cscode)
    {
        logger ??= (ILogger<LazyLoadingComplier>)Type.GetType("RSM.ServiceLocator, RSM.Core")?.GetMethod("GetService")?.MakeGenericMethod(typeof(ILogger<LazyLoadingComplier>))?.Invoke(null, null);
        if (string.IsNullOrWhiteSpace(cscode)) return Run<Assembly>(null, _ => logger?.LogDebug("cscode is null"));
        var key = Md5(cscode);
        logger?.LogDebug($"MD5:{key} cscode:{Environment.NewLine}{cscode}");
        if (Cache.TryGetValue(key, out var assembly)) return assembly;
        while (true)
        {
            try
            {
                AssemblyCSharpBuilder build = new AssemblyCSharpBuilder($"{DomainName}.{key}") { Domain = Domain }.UseNatashaFileOut().EnableNullableCompile();
                if (File.Exists(build.DllFilePath) && new FileInfo(build.DllFilePath).Length > 0)
                    return Run(Cache[key] = Domain.LoadFromStream(File.Open(build.DllFilePath, FileMode.Open)), e => logger?.LogDebug($"MD5:{key} Cache Result:{e.FullName}"));
                build.Add(cscode);
                return Run(Cache[key] = build.GetAssembly(), e => logger?.LogDebug($"MD5:{key} Build Result:{e.FullName}"));
            }
            catch (Exception e)
            {
                logger?.LogError(e, $"FreeSql.Extensions.LazyLoading,Error");
                Thread.Sleep(500);
            }
        }
    }
    internal static string Md5(string input)
    {
        using var md5 = MD5.Create();
        var hash = md5.ComputeHash(Encoding.UTF8.GetBytes(input));
        var sb = new StringBuilder();
        foreach (var b in hash) sb.Append(b.ToString("x2"));
        return sb.ToString();
    }
    internal static T Run<T>(T input, Action<T> action)
    {
        action(input);
        return input;
    }
}

```
包版本
```
	<ItemGroup>
		<PackageReference Include="FreeSql" Version="3.2.696" />
		<PackageReference Include="DotNetCore.Natasha.CSharp" Version="4.2.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
	</ItemGroup>
```

**Comment by sungyow** [comment]
“长时间运行之后”可能不准确，应该是程序停止运行后用户访问页面，程序被iis唤醒。
像部署后、手动触发iis站点重新启动都能正常运行，基本是每天早上刚一访问就会出错。

**Comment by 256051** [comment]
现在又有这个问题了！
