### ISSUE TITLE
导航属性偶发性出现 System.Exception: Unable to cast object of type 'System.Guid' to type 'System.String'.

### ISSUE THREAD

**Issue by hd2y** [dotnetcore/FreeSql#1632]
导航属性查询有时会报错，一旦报错后续的查询都会出现该异常。出现问题后，重启程序有一定概率恢复正常。

FreeSql 版本：`FreeSql.All v3.2.690.0`

查询代码：
```c#
var shipOrderItemId = new Guid("63AEBDD1-8312-4FA5-8911-FFFF0068B3F5");

var shipOrder = freeSql.Select<WMS_ShipOrderItem>()
                .Where(t => t.Id == shipOrderItemId)
                .Include(t => t.ShipOrder)
                .Include(t => t.MaterialProperty)
                .First();
```

生成SQL：
```sql
SELECT TOP 1 a.[Id], a.[AlloactedPkgQuantity], a.[BatchNo], a.[Comments], a.[CreationTime], a.[Creator], a.[CreatorId], a.[CustomerId], a.[DepartmentId], a.[ErpCode], a.[ExpectedPkgQuantity], a.[ExpirationDateFrom], a.[ExpirationDateTo], a.[LastModificationTime], a.[LastModifier], a.[LastModifierId], a.[MaterialId], a.[MaterialPropertyId], a.[MergeFeatureCode], a.[Obasis], a.[OwnerUser], a.[PackageUnitId], a.[PickedPkgQuantity], a.[ProductionDateFrom], a.[ProductionDateTo], a.[Qcstatus], a.[QualityGrade], a.[RowNo], a.[ShipOrderId], a.[ShippedPkgQuantity], a.[Str1], a.[Str10], a.[Str2], a.[Str3], a.[Str4], a.[Str5], a.[Str6], a.[Str7], a.[Str8], a.[Str9], a.[SupplierId], a.[WarehouseId], a.[WaveId], a.[WorkGroupId], a.[WorkLineId], a.[XOwner], 
a__MaterialProperty.[Id] as47, a__MaterialProperty.[AStartTime], a__MaterialProperty.[BatchNo] as49, a__MaterialProperty.[CreationTime] as50, a__MaterialProperty.[Creator] as51, a__MaterialProperty.[CreatorId] as52, a__MaterialProperty.[ExpiredTime], a__MaterialProperty.[HashCode], a__MaterialProperty.[InboundTime], a__MaterialProperty.[LastModificationTime] as56, a__MaterialProperty.[LastModifier] as57, a__MaterialProperty.[LastModifierId] as58, a__MaterialProperty.[M_Str1], a__MaterialProperty.[M_Str10], a__MaterialProperty.[M_Str11], a__MaterialProperty.[M_Str12], a__MaterialProperty.[M_Str13], a__MaterialProperty.[M_Str14], a__MaterialProperty.[M_Str15], a__MaterialProperty.[M_Str16], a__MaterialProperty.[M_Str17], a__MaterialProperty.[M_Str18], a__MaterialProperty.[M_Str19], a__MaterialProperty.[M_Str2], a__MaterialProperty.[M_Str20], a__MaterialProperty.[M_Str21], a__MaterialProperty.[M_Str22], a__MaterialProperty.[M_Str23], a__MaterialProperty.[M_Str24], a__MaterialProperty.[M_Str25], a__MaterialProperty.[M_Str26], a__MaterialProperty.[M_Str27], a__MaterialProperty.[M_Str28], a__MaterialProperty.[M_Str29], a__MaterialProperty.[M_Str3], a__MaterialProperty.[M_Str30], a__MaterialProperty.[M_Str31], a__MaterialProperty.[M_Str32], a__MaterialProperty.[M_Str33], a__MaterialProperty.[M_Str34], a__MaterialProperty.[M_Str35], a__MaterialProperty.[M_Str36], a__MaterialProperty.[M_Str37], a__MaterialProperty.[M_Str38], a__MaterialProperty.[M_Str39], a__MaterialProperty.[M_Str4], a__MaterialProperty.[M_Str40], a__MaterialProperty.[M_Str5], a__MaterialProperty.[M_Str6], a__MaterialProperty.[M_Str7], a__MaterialProperty.[M_Str8], a__MaterialProperty.[M_Str9], a__MaterialProperty.[MaterialCategoryId], a__MaterialProperty.[MaterialId] as100, a__MaterialProperty.[PreservationDays], a__MaterialProperty.[ProductionTime], a__MaterialProperty.[PropertyRuleId], a__MaterialProperty.[QCStartTime], a__MaterialProperty.[ReceivedTime], a__MaterialProperty.[SourceOrderCode], a__MaterialProperty.[SupplierId] as107, a__MaterialProperty.[WarehouseId] as108, a__MaterialProperty.[XType], 
a__ShipOrder.[Id] as110, a__ShipOrder.[AlloactedPkgQuantity] as111, a__ShipOrder.[AllRules], a__ShipOrder.[BillTypeId], a__ShipOrder.[CarrierId], a__ShipOrder.[Comments] as115, a__ShipOrder.[ContactAddress], a__ShipOrder.[ContactCity], a__ShipOrder.[ContactCountry], a__ShipOrder.[ContactEmail], a__ShipOrder.[ContactFax], a__ShipOrder.[ContactMobile], a__ShipOrder.[ContactName], a__ShipOrder.[ContactPostcode], a__ShipOrder.[ContactProvince], a__ShipOrder.[ContactTelephone], a__ShipOrder.[CreationTime] as126, a__ShipOrder.[Creator] as127, a__ShipOrder.[CreatorId] as128, a__ShipOrder.[CustomerId] as129, a__ShipOrder.[DeliveryDate], a__ShipOrder.[DeliveryStartDate], a__ShipOrder.[Destination], a__ShipOrder.[DockId], a__ShipOrder.[ErpStatus], a__ShipOrder.[ExpectedPkgQuantity] as135, a__ShipOrder.[IntendShipDate], a__ShipOrder.[IsOffLine], a__ShipOrder.[LastModificationTime] as138, a__ShipOrder.[LastModifier] as139, a__ShipOrder.[LastModifierId] as140, a__ShipOrder.[OfLine], a__ShipOrder.[OperateStatus], a__ShipOrder.[OrderDate], a__ShipOrder.[OwnerId], a__ShipOrder.[PickedPkgQuantity] as145, a__ShipOrder.[Priority], a__ShipOrder.[ReceivedBy], a__ShipOrder.[RelatedBill1], a__ShipOrder.[RelatedBill2], a__ShipOrder.[RelatedBill3], a__ShipOrder.[RelationCode], a__ShipOrder.[ShipDate], a__ShipOrder.[ShippedPkgQuantity] as153, a__ShipOrder.[ShipToName], a__ShipOrder.[Str1] as155, a__ShipOrder.[Str2] as156, a__ShipOrder.[Str3] as157, a__ShipOrder.[Str4] as158, a__ShipOrder.[Str5] as159, a__ShipOrder.[TipMsg], a__ShipOrder.[TradingCompany], a__ShipOrder.[TrusteeBy], a__ShipOrder.[VehicleId], a__ShipOrder.[WhId], a__ShipOrder.[XCode], a__ShipOrder.[XStatus] 
FROM [WMS].[ShipOrderItem] a With(NoLock) 
LEFT JOIN [WMS].[ShipOrder] a__ShipOrder With(NoLock) ON a__ShipOrder.[Id] = a.[ShipOrderId] 
LEFT JOIN [WMS].[MaterialProperty] a__MaterialProperty With(NoLock) ON a__MaterialProperty.[Id] = a.[MaterialPropertyId] 
WHERE (a.[Id] = 'f36cd816-0736-49ca-8f79-ffff081f2c6c')
```

堆栈跟踪信息：
```txt
System.Exception: Unable to cast object of type 'System.Guid' to type 'System.String'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.
   at lambda_method(Closure , Type , Int32[] , DbDataReader , Int32 , CommonUtils )
   at FreeSql.Internal.Utils.ExecuteArrayRowReadClassOrTuple(String flagStr, Type typeOrg, Int32[] indexes, DbDataReader row, Int32 dataIndex, CommonUtils _commonUtils)
   at lambda_method(Closure , IFreeSql , DbDataReader )
   at FreeSql.Internal.CommonProvider.Select0Provider`2.<>c__DisplayClass64_0.<ToListAfPrivate>b__0(FetchCallbackArgs`1 fetch)
   at FreeSql.Internal.CommonProvider.AdoProvider.<>c__DisplayClass78_0.<ExecuteReader>b__0(FetchCallbackArgs`1 fetch, Int32 result)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReader(DbConnection connection, DbTransaction transaction, Action`1 fetchHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivate(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListPrivate(GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToList(Boolean includeNestedMembers)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.ToList(Boolean includeNestedMembers)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToList()
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToOne()
   at FreeSql.Internal.CommonProvider.Select0Provider`2.First()
```

实体代码：
```c#
	[JsonObject(MemberSerialization.OptIn), Table(Name = "WMS.ShipOrder", DisableSyncStructure = true)]
	public partial class WMS_ShipOrder {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Id { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? AlloactedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(StringLength = 50)]
		public string AllRules { get; set; }

		[JsonProperty]
		public Guid BillTypeId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000000");

		[JsonProperty]
		public Guid? CarrierId { get; set; }

		[JsonProperty, Column(StringLength = -2)]
		public string Comments { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactAddress { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactCity { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactCountry { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactEmail { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactFax { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactMobile { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactName { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactPostcode { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactProvince { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ContactTelephone { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime CreationTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Creator { get; set; }

		[JsonProperty]
		public Guid? CreatorId { get; set; }

		[JsonProperty]
		public Guid? CustomerId { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? DeliveryDate { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? DeliveryStartDate { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Destination { get; set; }

		[JsonProperty]
		public Guid? DockId { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ErpStatus { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? ExpectedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? IntendShipDate { get; set; }

		[JsonProperty]
		public bool? IsOffLine { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? LastModificationTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string LastModifier { get; set; }

		[JsonProperty]
		public Guid? LastModifierId { get; set; }

		[JsonProperty]
		public int? OfLine { get; set; } = 0;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string OperateStatus { get; set; } = "";

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? OrderDate { get; set; }

		[JsonProperty]
		public Guid? OwnerId { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? PickedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty]
		public int? Priority { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ReceivedBy { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string RelatedBill1 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string RelatedBill2 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string RelatedBill3 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string RelationCode { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ShipDate { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? ShippedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(StringLength = 50)]
		public string ShipToName { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str1 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str2 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str3 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str4 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str5 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string TipMsg { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string TradingCompany { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string TrusteeBy { get; set; }

		[JsonProperty]
		public Guid? VehicleId { get; set; }

		[JsonProperty]
		public Guid WhId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000000");

		[JsonProperty, Column(StringLength = 50)]
		public string XCode { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string XStatus { get; set; }

	}

	[JsonObject(MemberSerialization.OptIn), Table(Name = "WMS.ShipOrderItem", DisableSyncStructure = true)]
	public partial class WMS_ShipOrderItem {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Id { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? AlloactedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(StringLength = 50)]
		public string BatchNo { get; set; }

		[JsonProperty, Column(StringLength = -2)]
		public string Comments { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime CreationTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Creator { get; set; }

		[JsonProperty]
		public Guid? CreatorId { get; set; }

		[JsonProperty]
		public Guid? CustomerId { get; set; }

		[JsonProperty]
		public Guid? DepartmentId { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string ErpCode { get; set; }

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? ExpectedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ExpirationDateFrom { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ExpirationDateTo { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? LastModificationTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string LastModifier { get; set; }

		[JsonProperty]
		public Guid? LastModifierId { get; set; }

		[JsonProperty]
		public Guid MaterialId { get; set; }

		[JsonProperty]
		public Guid MaterialPropertyId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000000");

		[JsonProperty, Column(StringLength = 50)]
		public string MergeFeatureCode { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Obasis { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string OwnerUser { get; set; }

		[JsonProperty]
		public Guid PackageUnitId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000000");

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? PickedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ProductionDateFrom { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ProductionDateTo { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Qcstatus { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string QualityGrade { get; set; }

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty]
		public Guid ShipOrderId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000000");

		[JsonProperty, Column(DbType = "decimal(18,6)")]
		public decimal? ShippedPkgQuantity { get; set; } = 0.0M;

		[JsonProperty, Column(StringLength = 50)]
		public string Str1 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str10 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str2 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str3 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str4 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str5 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str6 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str7 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str8 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Str9 { get; set; }

		[JsonProperty]
		public Guid? SupplierId { get; set; }

		[JsonProperty]
		public Guid? WarehouseId { get; set; }

		[JsonProperty]
		public Guid WaveId { get; set; }

		[JsonProperty]
		public Guid? WorkGroupId { get; set; }

		[JsonProperty]
		public Guid? WorkLineId { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string XOwner { get; set; }

	}

	[JsonObject(MemberSerialization.OptIn), Table(Name = "WMS.MaterialProperty", DisableSyncStructure = true)]
	public partial class WMS_MaterialProperty {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Id { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? AStartTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string BatchNo { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime CreationTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string Creator { get; set; }

		[JsonProperty]
		public Guid? CreatorId { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ExpiredTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string HashCode { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? InboundTime { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? LastModificationTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string LastModifier { get; set; }

		[JsonProperty]
		public Guid? LastModifierId { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str1 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str10 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str11 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str12 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str13 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str14 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str15 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str16 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str17 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str18 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str19 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str2 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str20 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str21 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str22 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str23 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str24 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str25 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str26 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str27 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str28 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str29 { get; set; }

		[JsonProperty, Column(StringLength = -2)]
		public string M_Str3 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str30 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str31 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str32 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str33 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str34 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str35 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str36 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str37 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str38 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str39 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str4 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str40 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str5 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str6 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str7 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str8 { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string M_Str9 { get; set; }

		[JsonProperty]
		public Guid? MaterialCategoryId { get; set; }

		[JsonProperty]
		public Guid MaterialId { get; set; }

		[JsonProperty]
		public int? PreservationDays { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ProductionTime { get; set; }

		[JsonProperty]
		public Guid PropertyRuleId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000000");

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? QCStartTime { get; set; }

		[JsonProperty, Column(DbType = "datetime2")]
		public DateTime? ReceivedTime { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string SourceOrderCode { get; set; }

		[JsonProperty]
		public Guid? SupplierId { get; set; }

		[JsonProperty]
		public Guid? WarehouseId { get; set; }

		[JsonProperty, Column(StringLength = 50)]
		public string XType { get; set; }

	}

public partial class WMS_ShipOrder
{
    [JsonProperty]
    [Navigate(nameof(WMS_ShipOrderItem.ShipOrderId))]
    public List<WMS_ShipOrderItem> ShipOrderItem { get; set; }

    //[JsonProperty]
    //[Navigate(nameof(CustomerId))]
    //public WMS_Orgnization Customer { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(OwnerId))]
    //public WMS_Orgnization Owner { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(CarrierId))]
    //public WMS_Orgnization Carrier { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(DockId))]
    //public WMS_Dock Dock { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(WhId))]
    //public WMS_Warehouse Warehouse { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(BillTypeId))]
    //public WMS_BillType BillType { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(VehicleId))]
    //public WMS_Vehicle Vehicle { get; set; }
}

public partial class WMS_ShipOrderItem
{
    [JsonProperty]
    [Navigate(nameof(ShipOrderId))]
    public WMS_ShipOrder ShipOrder { get; set; }

    [JsonProperty]
    [Navigate(nameof(MaterialPropertyId))]
    public WMS_MaterialProperty MaterialProperty { get; set; }

    //[JsonProperty]
    //[Navigate(nameof(MaterialId))]
    //public WMS_Material Material { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(PackageUnitId))]
    //public WMS_PackageUnit PackageUnit { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(SupplierId))]
    //public WMS_Orgnization Supplier { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(CustomerId))]
    //public WMS_Orgnization Customer { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(DepartmentId))]
    //public WMS_Orgnization Department { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(WarehouseId))]
    //public WMS_Warehouse Warehouse { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(WorkGroupId))]
    //public WMS_WorkGroup WorkGroup { get; set; }
    //
    //[JsonProperty]
    //[Navigate(nameof(WorkLineId))]
    //public WMS_WorkLine WorkLine { get; set; }
}
```

**Comment by 2881099** [comment]
表面看，是类型转换问题。

最好提供一个可以复现的，可运行的项目
