### ISSUE TITLE
Fatal error in Unity CIL Linker

### ISSUE THREAD

**Issue by 2022Cyberpunk** [dotnetcore/FreeSql#1649]
#### 问题描述及重现代码：

```c#
// c# code
```

#### 数据库版本
Unity2021.3.16f1
#### 安装的Nuget包
Put the dll file in the plugins folder of the unity project Asetts:
FreeSql.3.2.801
FreeSql.Provider.Sqlite.3.2.801

#### .net framework/. net core？ 及具体版本
net40
![企业微信截图_16984108822423](https://github.com/dotnetcore/FreeSql/assets/114492189/ac299ee8-2ce4-4beb-9bb2-5cf6c9371362)

**Comment by 2881099** [comment]
System.Data.Sqlite.dll

测试一下这个库，是否能使用

**Comment by 2022Cyberpunk** [comment]
freeSql是不是不支持unity？有问题的是FreeSql.Provider.Sqlite.dll，打包时会报错。

**Comment by 9a6c** [comment]
Building Library\Bee\artifacts\Android\ManagedStripped failed with output:
D:\unitys\Unity 2021.3.6f1\Editor\Data\il2cpp\build\deploy\UnityLinker.exe --search-directory=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed --out=Library/Bee/artifacts/Android/ManagedStripped --include-link-xml=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed\MethodsToPreserve.xml --include-link-xml=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed\TypesInScenes.xml --include-link-xml=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed\SerializedTypes.xml --include-link-xml=D:\svn\rensheju-mmo\client\Temp\burst.link.xml --include-link-xml=D:/unitys/Unity 2021.3.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/AndroidNativeLink.xml --include-directory=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed --dotnetprofile=unityaot-linux --dotnetruntime=Il2Cpp --platform=Android --use-editor-options --engine-stripping-flag=EnableUnityConnect --engine-stripping-flag=EnablePerformanceReporting --engine-stripping-flag=EnableAnalytics --engine-modules-asset-file=D:/unitys/Unity 2021.3.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/modules.asset --editor-data-file=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/EditorToUnityLinkerData.json --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/kcp2k.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/MYTOOL.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/UnityEngine.UI.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Mirror.Transports.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/SQLite-net.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Beautify.Universal.Runtime.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Mirror.Authenticators.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Telepathy.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/NavMeshComponents.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Mirror.Components.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Mirror.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Unity.RenderPipelines.Universal.Runtime.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Unity.VisualEffectGraph.Runtime.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Mirror.Examples.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Unity.TextMeshPro.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Unity.RenderPipelines.Core.Runtime.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/UnityWebSocket.Runtime.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/EasyExcel.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/Controller2k.dll --include-unity-root-assembly=D:/svn/rensheju-mmo/client/Temp/StagingArea/Data/Managed/SimpleWebTransport.dll --print-command-line
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: FreeSql.AdoNetExtensions.GetCrud(IDbConnection): Error processing method 'FreeSql.AdoNetExtensions.GetCrud(IDbConnection)' in assembly 'FreeSql.dll'
 ---> System.InvalidOperationException: No action for the assembly FreeSql.Provider.Dameng, Version=3.2.821.0, Culture=neutral, PublicKeyToken=null defined
   at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.IsFullyPreserved(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.MarkTypeVisibleToReflection(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.<>c__DisplayClass20_4.<HandleCall>b__7()
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue)
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack)
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody)
   at Unity.Linker.Steps.UnityMarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context)
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Unity.Linker.UnityDriver.UnityRun(Boolean noProfilerAllowed, ILogger customLogger)
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(ILogger customLogger, Boolean noProfilerAllowed)
   at Unity.Linker.UnityDriver.RunDriver()
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)


您好，我遇到了相同的问题， 错误来自FreeSql.Provider.Dameng， 我尝试了很多方式， 是否是FreeSql.Provider.Dameng 不支持unity il2cpp方式？  因为我使用mono模式打包时可以了， 是否有解决方法。

**Comment by 9a6c** [comment]
已解决！
方法：升级unity版本， 升级mirror框架的版本(项目用到)， 新版本有il2cpp bug的修复， 目前已正常打包
