### ISSUE TITLE
使用ExecuteUpdatedAsync时若没有Set操作，会导致异常

### ISSUE THREAD

**Issue by LeaFrock** [dotnetcore/FreeSql#1694]
#### 问题描述及重现代码：

执行ExecuteAffrowsAsync时，若没有Set操作或SetIf条件均未命中，不执行任何操作且无异常。
执行ExecuteUpdatedAsync则必然抛出异常：

```
System.ArgumentException: 找不到 WHERE
   at FreeSql.SqlServer.Curd.SqlServerUpdate`1.<>c__DisplayClass8_0`1.<<RawExecuteUpdatedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeSql.Internal.CommonProvider.UpdateProvider`1.ToSqlFetchAsync(Func`2 fetchAsync)
   at FreeSql.SqlServer.Curd.SqlServerUpdate`1.RawExecuteUpdatedAsync[TReturn](IEnumerable`1 columns, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.UpdateProvider`1.<>c__DisplayClass66_0`1.<<SplitExecuteUpdatedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeSql.Internal.CommonProvider.UpdateProvider`1.SplitExecuteAsync(Int32 valuesLimit, Int32 parameterLimit, String traceName, Func`1 executeAsync, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.UpdateProvider`1.SplitExecuteUpdatedAsync[TReturn](Int32 valuesLimit, Int32 parameterLimit, IEnumerable`1 columns, CancellationToken cancellationToken)
```

示例代码如下：

```c#
await FreeSql.Update<MyTable>()
        .Where(t => t.Id == 1)
        .ExecuteUpdatedAsync();


await FreeSql.Update<MyTable>()
        .Where(t => t.Id == 1)
        .SetIf(false, t => t.P1 == 1)
        .SetIf(false, t => t.P2 == "2")
        .ExecuteUpdatedAsync();
```

不知两者行为是否可以一致？最好是均无操作也无异常，减少调用者的代码量。

#### 数据库版本

SqlServer 2016

#### 安装的Nuget包

3.2.806

#### .net framework/. net core？ 及具体版本

.NET 8

**Comment by LeaFrock** [comment]
新版本已修复，谢谢！
