### ISSUE TITLE
ClickHouse.Client升级7.0后批量插入失败

### ISSUE THREAD

**Issue by wangboshun** [dotnetcore/FreeSql#1721]
使用ClickHouse.Client升级7.0后批量插入失败，还原为6.8.1正常。
 
报错异常信息：
System.InvalidOperationException: Column names not initialized. Call InitAsync once to load column data
   at FreeSql.ClickHouse.Curd.ClickHouseInsert`1.RawExecuteAffrows()
   at FreeSql.ClickHouse.Curd.ClickHouseInsert`1.SplitExecuteAffrows(Int32 valuesLimit, Int32 parameterLimit)
   at FreeSql.ClickHouse.Curd.ClickHouseInsert`1.ExecuteAffrows() 

```c#
 _fsql.Insert(list).NoneParameter().ExecuteAffrows();
```

#### 数据库版本
clickhouse 23

#### 安装的Nuget包
3.2.810

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by 2881099** [comment]
7.0 有什么变化，可以引用 FreeSql.Provider.Clickhouse.csproj 到项目内，之后 PR 贡献提交

**Comment by wangboshun** [comment]
> 7.0 有什么变化，可以引用 FreeSql.Provider.Clickhouse.csproj 到项目内，之后 PR 贡献提交

还没有研究有什么变化，不知道是什么原因导致错误的
