### ISSUE TITLE
发布出去的API 偶发性地报这个错误Non-static method requires a target.

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#1734]
#### 问题描述及重现代码：
发布出去的API 偶发性地报这个错误，没找到原因
Non-static method requires a target.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionBinary(String oper, Expression leftExp, Expression rightExp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionBinary(String oper, Expression leftExp, Expression rightExp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionWhereLambda(List`1 _tables, Expression exp, BaseDiyMemberExpression diymemexp, List`1 whereGlobalFilter, List`1 dbParams)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalWhere(Expression exp)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.WhereIf(Boolean condition, Expression`1 exp)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.Where(Expression`1 exp)
   at FreeSql.DbSet`1.Where(Expression`1 exp)

```c#
        List<T> GetList<T, TKey>(Expression<Func<T, bool>> predicate, Expression<Func<T, TKey>> order, SortType sortType) where T : class
        {
            List<T> list = null;// DataDbContext<T> 继承自 DbContext
            using (DbContext dbContext = new DataDbContext<T>(ConnectionString))
            {
                if (predicate == null)
                {
                    list = dbContext.Set<T>().OrderBy(order).ToList();
                }
                else
                {
                    list = dbContext.Set<T>().Where<T>(predicate).OrderBy(order).ToList();
                }
            }
            return list;
        }
```

#### 数据库版本
mysql 8.0.25

#### 安装的Nuget包
FreeSql.All  3.2.500

#### .net framework/. net core？ 及具体版本
dotnet 6.0.418
Microsoft.EntityFrameworkCore 6.0.4

**Comment by 2881099** [comment]
predicate 表达式树内的值为 null 的时候会报这个错，后面的版本优化过
