### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by dorsen110** [dotnetcore/FreeSql#1937]
#### 问题描述及重现代码：

```c#
code 
using var fsql = new FreeSqlBuilder().UseConnectionString(DataType.MySql, connectionString).Build();
var query = await fsql.Ado.CommandFluent(sql).CommandType(CommandType.StoredProcedure).CommandTimeout(60).QuerySingleAsync<xxx>();

异常
System.Exception: 【FreeSql: Master Database】Status unavailable, waiting for recovery. Index was outside the bounds of the array.
 ---> System.Exception: 【FreeSql: Master Database】Status unavailable, waiting for recovery. Index was outside the bounds of the array.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at MySql.Data.MySqlClient.MySqlPoolManager.GetPoolAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at FreeSql.MySql.MySqlConnectionPoolPolicy.OnGet(Object`1 obj)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.GetAsync()
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.AdoProvider.QueryAsync[T](Type resultType, DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   at FreeSql.Internal.Model.AdoCommandFluent.QuerySingleAsync[T](CancellationToken cancellationToken)

#### 数据库版本
mysql8.4

#### 安装的Nuget包
		<PackageReference Include="MySql.Data" Version="8.4.0" />
		<PackageReference Include="FreeSql" Version="3.2.833" />
		<PackageReference Include="FreeSql.DbContext" Version="3.2.833" />
		<PackageReference Include="FreeSql.Provider.MySql" Version="3.2.833" />
		<PackageReference Include="FreeSql.Provider.SqlServer" Version="3.2.833" />

#### .net framework/. net core？ 及具体版本
net7.0

**Comment by 2881099** [comment]
UseAdoConnectionPool(true)

FreeSql.Prpvider.MySqlConnector

两个都试试

**Comment by dorsen110** [comment]
出现了新的问题，查询不报错30s还未查询到结果，分析了sql并非满慢sql。连接串是这样的
Data Source=xxxxx.rds.aliyuncs.com;Port=3306;User ID=xxx;Password=xxxxx;Initial Catalog=xxxxxxl;Charset=utf8mb4;SslMode=none;Max pool size=10;Connection LifeTime=20

**Comment by 2881099** [comment]
错误堆栈？

**Comment by dorsen110** [comment]
没有报错。30s后客户端会主动断开

**Comment by dorsen110** [comment]
UseAdoConnectionPool(true); 有用
