### ISSUE TITLE
关于postgresql 的 【主库】状态不可用，等待后台检查程序恢复方可使用。Exception while reading from stream

### ISSUE THREAD

**Issue by pigwing** [dotnetcore/FreeSql#194]
**数据库连接已经添加了Connection LifeTime=20**
但是依然发生【主库】状态不可用，等待后台检查程序恢复方可使用。Exception while reading from stream
相关的相关资料都是指向command timeout的操作超时.

**Comment by 2881099** [comment]
Command Timeout=300 连接串可以加这个，不知是否加上了

这个错误多久触发一次，偶发性还是？

**Comment by pigwing** [comment]
没有官方默认是30的.
[https://www.npgsql.org/doc/connection-string-parameters.html#timeouts-and-keepalive](url)
目前只用了官方默认值

**Comment by pigwing** [comment]
> 这个错误多久触发一次，偶发性还是？

基本明天都会触发持续几分钟然后恢复

**Comment by 2881099** [comment]
方便上传一点重要日志吗

**Comment by pigwing** [comment]
【主库】恢复检查时间：2020/1/20 下午8:12:40
[41m[30mfail[39m[22m[49m: ECO.AirCompressor.DataCollection.Controllers.CollectionController[0]
      Exception while reading from stream
[41m[30mfail[39m[22m[49m: ECO.AirCompressor.DataCollection.Controllers.CollectionController[0]
         at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, ValueTuple`2 pc, Exception e, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalarAsync(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
         at ECO.Data.DataTableFreeSqlRepository.ExistingTableAsync(String tableName) in C:\Users\xpigw\OneDrive\后台服务\ECOAirCompressorDataCollection\ECOAirCompressorDataCollection\ECO.Data\DataTableFreeSqlRepository.cs:line 19
         at ECO.Data.HistoryStatusFreeSqlRepository.InsertAsync(String tableName, List`1 historyStatuses, TableExistingAsync tableExistingAsync) in C:\Users\xpigw\OneDrive\后台服务\ECOAirCompressorDataCollection\ECOAirCompressorDataCollection\ECO.Data\HistoryStatusFreeSqlRepository.cs:line 17
         at ECO.AirCompressor.DataCollection.Controllers.CollectionController.Post(List`1 transferDataLogs) in C:\Users\xpigw\OneDrive\后台服务\ECOAirCompressorDataCollection\ECOAirCompressorDataCollection\ECO.AirCompressor.DataCollection\Controllers\CollectionController.cs:line 213
[41m[30mfail[39m[22m[49m: ECO.AirCompressor.DataCollection.Controllers.CollectionController[0]
      【主库】状态不可用，等待后台检查程序恢复方可使用。Exception while reading from stream
[41m[30mfail[39m[22m[49m: ECO.AirCompressor.DataCollection.Controllers.CollectionController[0]
         at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, ValueTuple`2 pc, Exception e, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
         at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalarAsync(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
         at ECO.Data.DataTableFreeSqlRepository.ExistingTableAsync(String tableName) in C:\Users\xpigw\OneDrive\后台服务\ECOAirCompressorDataCollection\ECOAirCompressorDataCollection\ECO.Data\DataTableFreeSqlRepository.cs:line 19
         at ECO.Data.HistoryStatusFreeSqlRepository.InsertAsync(String tableName, List`1 historyStatuses, TableExistingAsync tableExistingAsync) in C:\Users\xpigw\OneDrive\后台服务\ECOAirCompressorDataCollection\ECOAirCompressorDataCollection\ECO.Data\HistoryStatusFreeSqlRepository.cs:line 17
         at ECO.AirCompressor.DataCollection.Controllers.CollectionController.Post(List`1 transferDataLogs) in C:\Users\xpigw\OneDrive\后台服务\ECOAirCompressorDataCollection\ECOAirCompressorDataCollection\ECO.AirCompressor.DataCollection\Controllers\CollectionController.cs:line 213
【主库】已恢复工作
【主库】恢复检查时间：2020/1/20 下午8:13:05

**Comment by 2881099** [comment]
看上去有两个可能：

1、Command 执行超时，超过30秒，可以从日志时间间隔，看看是不是这个的原因

2、空闲超过服务器设定被回收了，如果设置为20秒，检查日志排除这个可能

**Comment by pigwing** [comment]
以前用dapper的时候没发生过这个异常.但是是手动写sql的.这个问题能不能通过freesql的相关aop捕获慢查询?

**Comment by 2881099** [comment]
方式一：CRUD 审计

```csharp
fsql.Aop.CurdAfter = (s, e) => {
	if (e.ElapsedMilliseconds > 200) {
		//记录日志
		//发送短信给负责人
	}
};
```

方式二：new FreeSqlBuilder.UseMonitorCommand

```csharp
static IFreeSql fsql = new FreeSqlBuilder()...
   ...
   .UseMonitorCommand(cmd => {}, (cmd, log) => Console.WriteLine(log))
   .Build();
```

UseMonitorCommand 的第二个委托参数，默认为记录 > 100ms 的日志

```csharp
                if (e == null && ts.TotalMilliseconds > 100)
                    Trace.WriteLine(logtxt.Insert(0, $"{pool?.Policy.Name}（执行SQL）语句耗时过长{ts.TotalMilliseconds}ms\r\n{cmd.CommandText}\r\n").ToString());
                else
                    logtxt.Insert(0, $"{pool?.Policy.Name}（执行SQL）耗时{ts.TotalMilliseconds}ms\r\n{cmd.CommandText}\r\n").ToString();
```

**Comment by 2881099** [comment]
1.1.0-preview6 我把 Connection LifeTime=20 作成了默认设置

**Comment by pigwing** [comment]
找到问题了.是command timeout = 30 官方默认的太短了.阿里云的写入IO不够快.freeSql里面用到了批量insert,量一大,就会超出30ms.
