### ISSUE TITLE
和AspectCore.Extensions.DependencyInjection有冲突

### ISSUE THREAD

**Issue by yus1977** [dotnetcore/FreeSql#258]
我使用了AspectCore.Extensions.DependencyInjection后，CreateHostBuilder(args).Build().Run()报错，应该是两个AOP有冲突。
 StackTrace:
   at AspectCore.Configuration.StringExtensions.Matches(String input, String pattern)
   at AspectCore.Configuration.Predicates.<>c__DisplayClass0_0.<ForNameSpace>b__0(MethodInfo method)
   at AspectCore.DynamicProxy.ConfigureAspectValidationHandler.<>c__DisplayClass5_0.<Invoke>b__0(AspectPredicate x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AspectCore.DynamicProxy.ConfigureAspectValidationHandler.Invoke(AspectValidationContext context, AspectValidationDelegate next)
   at AspectCore.DynamicProxy.AspectValidatorBuilder.<>c__DisplayClass1_1.<.ctor>b__2(AspectValidationContext method)
   at AspectCore.DynamicProxy.OverwriteAspectValidationHandler.Invoke(AspectValidationContext context, AspectValidationDelegate next)
   at AspectCore.DynamicProxy.AspectValidatorBuilder.<>c__DisplayClass1_1.<.ctor>b__2(AspectValidationContext method)
   at AspectCore.DynamicProxy.CacheAspectValidationHandler.<>c__DisplayClass4_0.<Invoke>b__0(AspectValidationContext tuple)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AspectCore.DynamicProxy.CacheAspectValidationHandler.Invoke(AspectValidationContext context, AspectValidationDelegate next)
   at AspectCore.DynamicProxy.AspectValidatorBuilder.<>c__DisplayClass1_1.<.ctor>b__2(AspectValidationContext method)
   at AspectCore.DynamicProxy.AspectValidator.Validate(MethodInfo method, Boolean isStrictValidation)
   at AspectCore.DynamicProxy.AspectValidatorExtensions.Validate(IAspectValidator aspectValidator, Type type, Boolean isStrictValidation)
   at AspectCore.DependencyInjection.ServiceValidator.TryValidate(ServiceDefinition definition, Type& implementationType)
   at AspectCore.DependencyInjection.ServiceTable.MakProxyService(ServiceDefinition service)
   at AspectCore.DependencyInjection.ServiceTable.Populate(IEnumerable`1 services)
   at AspectCore.DependencyInjection.ServiceResolver..ctor(IServiceContext serviceContext)
   at AspectCore.DependencyInjection.ServiceContainerBuildExtensions.Build(IServiceContext serviceContext)
   at AspectCore.Extensions.DependencyInjection.ServiceContextProviderFactory.CreateServiceProvider(IServiceContext contextBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/233

**Comment by yus1977** [comment]
thank very mush!

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql.DynamicProxy

有机会可以试试这个库，前阵子写的
