### ISSUE TITLE
自定义解析枚举转换求助

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#269]
不废话，上代码
```C#
[ExpressionCall]
public static class DbFunc
{
    static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();
    //自定义数据库方法
    public static TOut FuncExpression<T1, T2, TOut>(string func, T1 p1, T2 p2)
    {
        var up = context.Value;
        var values = up.ParsedContent.Values.ToArray();
        context.Value.Result = $"{func}({values[1]}, {values[2]})";
        return default;
    }
}
public enum EDIUseMode : byte
{
    OutPut = 1,
    Import = 2,
    Both = 3,
}
[Table(Name = "EDI")]
public class Edi
{
    [Column(Name = "EDI_ID")] public long Id { get; set; }
    [Column(Name = "EDI_USE_MODE")] public EDIUseMode? UseMode { get; set; }
}
......
var sql1 = fsql.Select<Edi>()
    .Where(a =>
        DbFunc.FuncExpression<EDIUseMode?, EDIUseMode, EDIUseMode>("ISNULL", a.UseMode, EDIUseMode.Both) == EDIUseMode.Both)
    .ToSql(); //这么写报错：ExpressionTree 转换类型错误，值(a.[EDI_USE_MODE])，类型(System.String)，目标类型(System.Nullable`1[EDIUseMode])，Requested value 'a.[EDI_USE_MODE]' was not found.
var sql2 = fsql.Select<Edi>()
    .Where(a =>
        DbFunc.FuncExpression<int?, int, int>("ISNULL", (int)a.UseMode, (int)EDIUseMode.Both) == (int)EDIUseMode.Both)
    .ToSql(); //这么写就不报错
```
调试发现没有进入FuncExpression前就报错了，是不是不能用枚举？
```
ExpressionTree 转换类型错误，值(a.[EDI_USE_MODE])，类型(System.String)，目标类型(System.Nullable`1[EDIUseMode])，Requested value 'a.[EDI_USE_MODE]' was not found.

at FreeSql.Internal.Utils.GetDataReaderValue(Type type, Object value) in D:\Projects\github\FreeSql\FreeSql\Internal\UtilsExpressionTree.cs:line 2048
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 649
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 599
   at FreeSql.Internal.CommonExpression.ExpressionBinary(String oper, Expression leftExp, Expression rightExp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 482
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 1342
   at FreeSql.Internal.CommonExpression.ExpressionWhereLambda(List`1 _tables, Expression exp, Func`2 getSelectGroupingMapString, List`1 whereCascadeExpression, List`1 dbParams) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 386
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalWhere(Expression exp) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select0Provider.cs:line 1154
   at FreeSql.Internal.CommonProvider.Select1Provider`1.WhereIf(Boolean condition, Expression`1 exp) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select1Provider.cs:line 289
   at FreeSql.Internal.CommonProvider.Select1Provider`1.Where(Expression`1 exp) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select1Provider.cs:line 284
```

**Comment by 2881099** [comment]
收到，这个问题是入参数的时候转换失败了

**Comment by 2881099** [comment]
另外 isnull 这种 sql 直接用 c# 语法就可以实现。

Where(a => (a.UseMode ?? EDIUseMode.None) == EDIUseMode.None)

**Comment by tky753** [comment]
好的，谢谢
