### ISSUE TITLE
IService，Service 事务时注入服务问题

### ISSUE THREAD

**Issue by wmmbskys** [dotnetcore/FreeSql#336]
是否这种方式不行，只能直接调用 SongService，不继承 ISongService？

public interface ISongService
    {
        void Test1();
    }

    public class SongService: ISongService
    {
        BaseRepository<Song> _repoSong;
        BaseRepository<Detail> _repoDetail;
        public SongService(BaseRepository<Song> repoSong, BaseRepository<Detail> repoDetail)
        {
            _repoSong = repoSong;
            _repoDetail = repoDetail;
        }

        [Transactional(Propagation = Propagation.Nested)] //sqlite 不能嵌套事务，会锁库的
        public virtual void Test1()
        {
            _repoSong.Insert(new Song());
            _repoDetail.Insert(new Detail());
        }
    }

InvalidOperationException: No service for type 'aspnetcore_transaction.Controllers.ISongService' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinder.BindModelAsync(ModelBindingContext bindingContext)
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, object value)
Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider+<>c__DisplayClass0_0+<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by 2881099** [comment]
居然漏掉了这个 issues，SongService 还是 ISongService 是注入方式的问题，还有跟动态代理库有关。

先关闭问题了。

**Comment by zhangkeyuan** [comment]
请问这个问题解决了吗

**Comment by 2881099** [comment]
> 请问这个问题解决了吗

这个不是问题啊，如果你注入 ISongService，反转使用的时候就用 ISongService。

如果注入 SongService，反转使用的时候用 ISongService 肯定报错啊。

**Comment by zhangkeyuan** [comment]
> > 请问这个问题解决了吗
> 
> 这个不是问题啊，如果你注入 ISongService，反转使用的时候就用 ISongService。
> 
> 如果注入 SongService，反转使用的时候用 ISongService 肯定报错啊。

注入的是： services.AddScoped<IMenuService, MenuService>();
反转是：private readonly IMenuService _menuService;

        public MenuController(IMenuService menuService)
        {
            _menuService = menuService;
        }
报错是：系统异常：Unable to resolve service for type 'Jxc.Platform.Application.Interface.IMenuService' while attempting to activate 'Jxc.Platform.Api.Controllers.v1.MenuController'.
      System.InvalidOperationException: Unable to resolve service for type 'Jxc.Platform.Application.Interface.IMenuService' while attempting to activate 'Jxc.Platform.Api.Controllers.v1.MenuController'.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
         at lambda_method149(Closure , IServiceProvider , Object[] )
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Gsharp.Middleware.ExceptionHandlerMiddleWare.Invoke(HttpContext context) in E:\Source\jxc_service_collection\src\Framework\Gsharp\Middleware\ExceptionHandlerMiddleWare.cs:line 28

**Comment by luoyunchong** [comment]
不要再用 `FreeSql.DynamicProxy`了，我测试了，用接口的Service的确不行。。

麻烦用 `Autofac`、`Castle.Core.` 老牌AOP和注入

```
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
        <PackageReference Include="Autofac.Extras.DynamicProxy" Version="5.0.0" />
        <PackageReference Include="Castle.Core.AsyncInterceptor" Version="1.7.0" />
```

可参考此文章  [AOP +FreeSql 跨方法异步事务](https://www.cnblogs.com/igeekfan/p/aop-freesql-autofac.html)

**Comment by zhangkeyuan** [comment]
好吧，我还说用FreeSql配套的FreeSql.DynamicProxy更好呢
