### ISSUE TITLE
mysqlconnector和mysql.data相同代码表现不同，嵌套方法事务问题This MySqlConnection is already in use

### ISSUE THREAD

**Issue by luoyunchong** [dotnetcore/FreeSql#457]
- 驱动
``` 
<!--<PackageReference Include="FreeSql.Provider.MySql" Version="1.9.0-preview0906" />-->
<PackageReference Include="FreeSql.Provider.MySqlConnector" Version="1.9.0-preview0906" />
```
```
[11:37:19 ERR] Connection id "0HLVN2V9CD1C8", Request id "0HLVN2V9CD1C8:00000001": An unhandled exception was thrown by the application. <s:Microsoft.AspNetCore.Server.Kestrel>
System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
at FreeSql.UnitOfWorkManager.Dispose()
at Autofac.Core.Disposer.DisposeAsync(Boolean disposing)
at Autofac.Core.Lifetime.LifetimeScope.DisposeAsync(Boolean disposing)
at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.DisposeAsync()
at Autofac.Extensions.DependencyInjection.AutofacServiceScope.DisposeAsync()
at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
atMicrosoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FireOnCompletedAwaited(Task currentTask, Stack`1 onCompleted)
```

我之前在事务会遇到如上问题。昨天 终于重现了。。。原来只有mysqlconnector会有问题。。我换成mysql.data，同样的代码，就不会出现这个错。

#### 逻辑如下（仅用于测试事务是否回滚写的异常）
在一个事务blogSerivce中调用了一个tagService，如果这个Service，没有在方法上写Transactional，在mysql.data的freesql驱动下，运行正常。虽然不是同一个事务，相当于在tagservice不在事务中运行，即挂起当前事务（Propagation.NotSupported）。

```
    /// <summary>
    /// 事务传播方式
    /// </summary>
    public enum Propagation
    {
        /// <summary>
        /// 以非事务方式执行操作，如果当前存在事务，就把当前事务挂起。
        /// </summary>
        NotSupported,
    }
```
- 在mysqlconnector下，不写Transactional，我们在前台一直请求此方法，就会出现This MySqlConnection is already in use的异常。导致服务暂时挂掉。

#### 此问题，可在TagService类的方法CreateAsync上加上Transactional即可解决。但二个类库表现不太一致。此问题能否在freesql层上解决，以挂起事务的情况运行。

- BlogService
```
        [Transactional]
        public virtual async Task<Blog> InsertAsync(CreateBlogDto createBlogDto)
        {
            Blog blog = _mapper.Map<Blog>(createBlogDto);
            blog.UpdateTime = DateTime.Now;
            await _blogRepository.InsertAsync(blog);

            await _tagService.CreateAsync(
                 new Tag()
                 {
                     IsDeleted = false,
                     TagName = createBlogDto.Title,
                     PostId = blog.Id
                 });
            if (createBlogDto.Title == "abcd")
            {
                throw new Exception("ff");
            }
            return blog;
        }
```

- TagService
```
        [Transactional(Propagation = Propagation.Required)]
        public virtual async Task CreateAsync(Tag tag)
        {
            List<Tag> tags = new List<Tag> { };
            tags.Add(new Tag()
            {
                TagName = "a",
                IsDeleted = false
            });
            tags.Add(tag);
            await _tagRepository.InsertAsync(tags);

            if (tag.TagName == "abc")
            {
                throw new Exception("exce");
            }
        }
```
### 完整的demo

[FreeSql-Transactional-MySqlConnector.zip](https://github.com/dotnetcore/FreeSql/files/5198945/FreeSql-Transactional-MySqlConnector.zip)

**Comment by 2881099** [comment]
经检查 demo 代码，发现 AOP 代码没有保证异步方法的顺序，导致 DbConnection 被同时使用的情况。

MySql.Data.dll 应该没有作这样的检测，所以没有抛出异常。

![Q8 _3QCN`J6QI%P(Z3Z`MW](https://user-images.githubusercontent.com/16286519/92682372-c07d4080-f362-11ea-9781-f9a4da4735fa.png)

如上：无法保证执行顺序，是有可能出现并发访问同一个 DbConnection 情况。异步，一定要全部 Task、async 到底，上面那个方法是同步的 void 不行。

**Comment by luoyunchong** [comment]
我发现我只把返回Task的方法改成异步，await async，就正常了。
```
      /// <summary>
        /// 拦截返回结果为Task的方法
        /// </summary>
        /// <param name="invocation"></param>
        public async void InterceptAsynchronous(IInvocation invocation)
        {
            await InternalInterceptAsynchronous(invocation);
        }

```
引用包
```
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
        <PackageReference Include="Autofac.Extras.DynamicProxy" Version="5.0.0" />
        <PackageReference Include="Castle.Core.AsyncInterceptor" Version="1.7.0" />
```
- 完整代码
```
  public class UnitOfWorkInterceptor : IInterceptor
    {
        private readonly UnitOfWorkAsyncInterceptor asyncInterceptor;

        public UnitOfWorkInterceptor(UnitOfWorkAsyncInterceptor interceptor)
        {
            asyncInterceptor = interceptor;
        }

        public void Intercept(IInvocation invocation)
        {
            asyncInterceptor.ToInterceptor().Intercept(invocation);
        }
    }

    public class UnitOfWorkAsyncInterceptor : IAsyncInterceptor
    {
        private readonly UnitOfWorkManager _unitOfWorkManager;
        private readonly ILogger<UnitOfWorkAsyncInterceptor> _logger;
        IUnitOfWork _unitOfWork;

        public UnitOfWorkAsyncInterceptor(UnitOfWorkManager unitOfWorkManager, ILogger<UnitOfWorkAsyncInterceptor> logger)
        {
            _unitOfWorkManager = unitOfWorkManager;
            _logger = logger;
        }

        private bool TryBegin(IInvocation invocation)
        {
            //_unitOfWork = _unitOfWorkManager.Begin(Propagation.Requierd);
            //return true;
            var method = invocation.MethodInvocationTarget ?? invocation.Method;
            var attribute = method.GetCustomAttributes(typeof(TransactionalAttribute), false).FirstOrDefault();
            if (attribute is TransactionalAttribute transaction)
            {
                _unitOfWork = _unitOfWorkManager.Begin(transaction.Propagation, transaction.IsolationLevel);
                return true;
            }

            return false;
        }

        /// <summary>
        /// 拦截同步执行的方法
        /// </summary>
        /// <param name="invocation"></param>
        public void InterceptSynchronous(IInvocation invocation)
        {
            if (TryBegin(invocation))
            {
                int? hashCode = _unitOfWork.GetHashCode();
                try
                {
                    invocation.Proceed();
                    _logger.LogInformation($"----- 拦截同步执行的方法-事务 {hashCode} 提交前----- ");
                    _unitOfWork.Commit();
                    _logger.LogInformation($"----- 拦截同步执行的方法-事务 {hashCode} 提交成功----- ");
                }
                catch
                {
                    _logger.LogError($"----- 拦截同步执行的方法-事务 {hashCode} 提交失败----- ");
                    _unitOfWork.Rollback();
                    throw;
                }
                finally
                {
                    _unitOfWork.Dispose();
                }
            }
            else
            {
                invocation.Proceed();
            }
        }

        /// <summary>
        /// 拦截返回结果为Task的方法
        /// </summary>
        /// <param name="invocation"></param>
        public async void InterceptAsynchronous(IInvocation invocation)
        {
            await InternalInterceptAsynchronous(invocation);
        }

        private async Task InternalInterceptAsynchronous(IInvocation invocation)
        {
            if (TryBegin(invocation))
            {
                string methodName = $"{invocation.MethodInvocationTarget.DeclaringType?.FullName}.{invocation.Method.Name}()";
                int? hashCode = _unitOfWork.GetHashCode();

                using (_logger.BeginScope("_unitOfWork:{hashCode}", hashCode))
                {
                    _logger.LogInformation($"----- async Task 开始事务{hashCode} {methodName}----- ");

                    invocation.Proceed();

                    try
                    {
                        await (Task)invocation.ReturnValue;
                        _unitOfWork.Commit();
                        _logger.LogInformation($"----- async Task 事务 {hashCode} Commit----- ");
                    }
                    catch (System.Exception)
                    {
                        _unitOfWork.Rollback();
                        _logger.LogError($"----- async Task 事务 {hashCode} Rollback----- ");
                        throw;
                    }
                }
            }
            else
            {
                invocation.Proceed();
            }
        }


        /// <summary>
        /// 拦截返回结果为Task<TResult>的方法
        /// </summary>
        /// <param name="invocation"></param>
        /// <typeparam name="TResult"></typeparam>
        public void InterceptAsynchronous<TResult>(IInvocation invocation)
        {
            invocation.ReturnValue = InternalInterceptAsynchronous<TResult>(invocation);
        }

        private async Task<TResult> InternalInterceptAsynchronous<TResult>(IInvocation invocation)
        {
            if (TryBegin(invocation))
            {
                string methodName = $"{invocation.MethodInvocationTarget.DeclaringType?.FullName}.{invocation.Method.Name}()";
                int hashCode = _unitOfWork.GetHashCode();
                _logger.LogInformation($"----- async Task<TResult> 开始事务{hashCode} {methodName}----- ");

                try
                {
                    invocation.Proceed();
                    TResult result = await (Task<TResult>)invocation.ReturnValue;
                    _unitOfWork.Commit();
                    _logger.LogInformation($"----- async Task<TResult> Commit事务{hashCode}----- ");
                    return result;
                }
                catch (System.Exception)
                {
                    _unitOfWork.Rollback();
                    _logger.LogError($"----- async Task<TResult> Rollback事务{hashCode}----- ");
                    throw;
                }
                finally
                {
                    _unitOfWork.Dispose();
                }
            }
            else
            {
                invocation.Proceed();
                TResult result = await (Task<TResult>)invocation.ReturnValue;
                return result;
            }

        }
    }
```
