### ISSUE TITLE
变量参数没赋值绑定

### ISSUE THREAD

**Issue by changzhuan** [dotnetcore/FreeSql#462]
FreeSql 1.8.1
初始化:

```c#
IFreeSql freeSql = new FreeSql.FreeSqlBuilder()
                        .UseConnectionString(FreeSql.DataType.Oracle, connectionStrings.DefaultConnection) 
                       .UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper)
                       .UseGenerateCommandParameterWithLambda(true)
                        .UseMonitorCommand(cmd =>
                          LogHelper.Debug(cmd.CommandText)
                        )
                        .Build();
```
实体类代码:

```c#
[Table(Name = "V_HospitalReport")]
    public class V_HospitalReport
    { 
        [Column(Name = "hospital_name")]
        public string HospitalName { get; set; }
      
        [Column(Name = "dep")]
        public string Dep { get; set; }
    
        [Column(Name = "instrna")]
        public string Instrna { get; set; }
   
        [Column(Name = "confirm_doctor_name")]
        public string ConfirmDoctorName { get; set; }
       
        [Column(Name = "Scheduled_Dttm")]
        public DateTime ScheduledDttm { get; set; } 
    }

 
    public class TotalDto
    {
        
        public long DayNum { get; set; }
 
        public long TotalNum { get; set; }
    }
```

查询代码:

```c#
  DateTime dateTime = DateTime.Now;
            ISelect<V_HospitalReport> select1 = freeSql.Select<V_HospitalReport>();
            ISelect<V_HospitalReport> select2 = freeSql.Select<V_HospitalReport>();


await freeSql.Select<V_HospitalReport>().ToOneAsync(a =>
             new TotalDto
             {
                 TotalNum = select1.Count(),
                 DayNum = select2.Where(b => b.ScheduledDttm.Date == dateTime.Date).Count()
             });
```

**Comment by changzhuan** [comment]
ORA-01008错误

**Comment by 2881099** [comment]
抱歉，这两天招黑较多，忙于口水之争，现在才有时候看问题。

ORA-01008错误，详细错误发一下，还有 SQL 打印出来，去控制台运行看看。

**Comment by changzhuan** [comment]
辛苦了

**Comment by changzhuan** [comment]
System.Exception: ORA-01008: ??????????
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01008: ??????????
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListMrPrivateAsync[TReturn](String sql, ReadAnonymousTypeAfInfo af, ReadAnonymousTypeOtherInfo[] otherData)

**Comment by changzhuan** [comment]
SELECT (SELECT count(1) 
    FROM "V_HOSPITALREPORT" a 
    WHERE ROWNUM < 2) as1, (SELECT count(1) 
    FROM "V_HOSPITALREPORT" b 
    WHERE (trunc(b."SCHEDULED_DTTM") = trunc(:exp_0)) AND ROWNUM < 2) as2 
FROM "V_HOSPITALREPORT" a 
WHERE ROWNUM < 2

**Comment by changzhuan** [comment]
就是参数没有赋值

**Comment by changzhuan** [comment]
记着之前Groupby的时候参数也发现没有赋值，后来你在1.7.1里面改了，现在这个子表查询也是参数没有赋值

**Comment by 2881099** [comment]
意思是之前没问题吗？

**Comment by changzhuan** [comment]
不是，之前是GroupBy有问题已经改了，现在刚刚才用到子表查询传参才发现这个问题

**Comment by 2881099** [comment]
排查了一下，目前这个子查询 List\<DbParameter> 只在 .Where 的时候向子查询传递。

.ToList 的时候没有传递，所以导致了该问题。测试中，都通过了会发布一个 preview 版本

**Comment by 2881099** [comment]
很简单的调整就行了，最近是非多，专不下心拖了这么长时间

**Comment by 2881099** [comment]
v1.9.0-preview0916 已发布，过几分钟之后更新一下试试

**Comment by changzhuan** [comment]
好的，谢谢

**Comment by changzhuan** [comment]
子表查询我用count，条件怎么会也带外面ToOneAsync的WHERE ROWNUM < 2

**Comment by changzhuan** [comment]
这样查出来的数据都是1了

**Comment by 2881099** [comment]
是有可能，看来子查询不能加 Limit(1)，只有 Any ToOne First 才需要加 Limit(1)。

WHERE ROWNUM < 2 是 .Count 默认加了 Limit(1)，是 bug。谢谢反馈

**Comment by changzhuan** [comment]
Count 默认加了 Limit(1)这个bug大概什么版本会修复，我现在先cmd.CommandText 里面Replace  WHERE ROWNUM < 2 和AND ROWNUM < 2 会不会影响其他的查询

**Comment by 2881099** [comment]
v1.9.0-preview0916 已发布，过几分钟之后更新一下试试

**Comment by changzhuan** [comment]
这效率没得说，再次感谢
