### ISSUE TITLE
FreeSql的UnitOfWork Commit的事务被using后，再次Commit问题

### ISSUE THREAD

**Issue by luoyunchong** [dotnetcore/FreeSql#503]
我发现 。FreeSql的UnitOfWork Commit时，是不是应该判断_tran.Connection!=null  
https://github.com/dotnetcore/FreeSql/blob/master/FreeSql.DbContext/UnitOfWork/UnitOfWork.cs
![image](https://user-images.githubusercontent.com/18613266/97382298-fd4aca00-1905-11eb-824d-c55450b3cba4.png)

因为配合 CAP时候，会在方法中用UnitOfWorkManager.Current.Commit()，如果using ICapTransaction 可能会把当前的事务using掉，在AOP会再次Commit时，就会报[ERR] Connection id "0HM3QICK5E3GI", Request id "0HM3QICK5E3GI:00000039": An unhandled exception was thrown by the application.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MySqlTransaction'.
   at FreeSql.UnitOfWorkManager.Dispose()
   at Autofac.Core.Disposer.DisposeAsync(Boolean disposing)
   at Autofac.Core.Lifetime.LifetimeScope.DisposeAsync(Boolean disposing)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.DisposeAsync()
   at Autofac.Extensions.DependencyInjection.AutofacServiceScope.DisposeAsync()
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnCompleted>g__ProcessEvents|227_0(HttpProtocol protocol, Stack`1 events)

CAP扩展方法
```
        public static void Commit(this ICapTransaction capTransaction, IUnitOfWork unitOfWork)
        {
            unitOfWork.Commit();
            capTransaction.Flush();
        }
```
[Transactional]特性标签就会开启事务，但在CAP中需要如下方式提交事务
```
                capTransaction.Commit(UnitOfWorkManager.Current);
```
CAP 发布消息
```
[Transactional]

              using ICapTransaction capTransaction = UnitOfWorkManager.Current.BeginTransaction(_capBus, false);
                await _capBus.PublishAsync(“Notification.CreateOrCancel,” new CreateNotificationDto()
                {
                    xxxxx
                });
                capTransaction.Commit(UnitOfWorkManager.Current);
            }
```

带[Transactional]会开启事务，自己提交事务。
```

        private async Task InternalInterceptAsynchronous(IInvocation invocation)
        {
                string methodName =
                    $"{invocation.MethodInvocationTarget.DeclaringType?.FullName}.{invocation.Method.Name}()";
                int? hashCode = _unitOfWork.GetHashCode();

                using (_logger.BeginScope("_unitOfWork:{hashCode}", hashCode))
                {
                    _logger.LogInformation($"----- async Task 开始事务{hashCode} {methodName}----- ");

                    invocation.Proceed();

                    try
                    {
                        await (Task)invocation.ReturnValue;
                        _unitOfWork.Commit();
                        _logger.LogInformation($"----- async Task 事务 {hashCode} Commit----- ");
                    }
                    catch (System.Exception)
                    {
                        _unitOfWork.Rollback();
                        _logger.LogError($"----- async Task 事务 {hashCode} Rollback----- ");
                        throw;
                    }
                    finally
                    {
                        _unitOfWork.Dispose();
                    }
                }
          
        }
```

在方法内可能using掉。所以通过判断dbTransaction，Connection是否不为null

```
  DbTransaction  dbTransaction= _unitOfWork.GetOrBeginTransaction();  
   if (dbTransaction != null&&dbTransaction.Connection!=null)
｛
    _unitOfWork.Commit();
｝
```

解决方法，多判断一层。
```
     private async Task InternalInterceptAsynchronous(IInvocation invocation)
        {
            string methodName =
                $"{invocation.MethodInvocationTarget.DeclaringType?.FullName}.{invocation.Method.Name}()";
            int? hashCode = _unitOfWork.GetHashCode();

            using (_logger.BeginScope("_unitOfWork:{hashCode}", hashCode))
            {
                _logger.LogInformation($"----- async Task 开始事务{hashCode} {methodName}----- ");

                invocation.Proceed();
                DbTransaction dbTransaction = null;

                try
                {
                    await (Task)invocation.ReturnValue;
                    dbTransaction= _unitOfWork.GetOrBeginTransaction(); 
                    if (dbTransaction != null&&dbTransaction.Connection!=null)
                    {
                        _unitOfWork.Commit();
                    }
                    _logger.LogInformation($"----- async Task 事务 {hashCode} Commit----- ");
                }
                catch (System.Exception)
                {
                    _unitOfWork.Rollback();
                    _logger.LogError($"----- async Task 事务 {hashCode} Rollback----- ");
                    throw;
                }
                finally
                {
                    if (dbTransaction != null && dbTransaction.Connection != null)
                    {
                        _unitOfWork.Dispose();
                    }
                }
            }
```

**Comment by 2881099** [comment]
现在这样处理，会让  Aop.TraceAfter 执行不了

**Comment by 2881099** [comment]
还有 EntityChangeReport.OnChange 委托也无法执行

**Comment by luoyunchong** [comment]
```
           if (_tran != null && _tran.Connection != null)
                {
                    _tran.Rollback();
                    isRollbacked = true;
                    _fsql?.Aop.TraceAfterHandler?.Invoke(this, new Aop.TraceAfterEventArgs(_tranBefore, "回滚", null));
                }
```

这样改呢。


```
           if (_tran != null )
            {
                    if(_tran.Connection != null)_tran.Rollback();
                    isRollbacked = true;
                    _fsql?.Aop.TraceAfterHandler?.Invoke(this, new Aop.TraceAfterEventArgs(_tranBefore, "回滚", null));
            }
```

**Comment by 2881099** [comment]
好的，我先按这样改

**Comment by luoyunchong** [comment]
FreeSql接入CAP的实践      https://www.cnblogs.com/igeekfan/p/cap_freesql_flush.html 



### FreeSql接入CAP(最简单的方式)

关于此问题的想法
- https://github.com/luoyunchong/DotNetCore.CAP.Provider/issues/1


我们还是引用各自官方的库
```
Install-Package DotNetCore.CAP.Dashboard
Install-Package DotNetCore.CAP.MySql
Install-Package DotNetCore.CAP.RabbitMQ
Install-Package FreeSql
Install-Package FreeSql.DbContext
Install-Package FreeSql.Provider.MySqlConnector
```
关于CAP集成的方式，配置项，这里不做详情，官方地址有中文： http://cap.dotnetcore.xyz/

- 代码参考。因为只有一个类，我们自行复制项目即可。
- https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Application/CapUnitOfWorkExtensions.cs

重写扩展方法，BeginTransaction。是基于IUnitOfWork的扩展。

提交事务调用Commit(IUnitOfWork)时，内部再通过反射调用 ICapTransaction中protected类型的方法Flush。


```
  public static class CapUnitOfWorkExtensions
    {

        public static void Flush(this ICapTransaction capTransaction)
        {
            capTransaction?.GetType().GetMethod("Flush", BindingFlags.Instance | BindingFlags.NonPublic)?.Invoke(capTransaction, null);
        }

       
        public static ICapTransaction BeginTransaction(this IUnitOfWork unitOfWork, ICapPublisher publisher, bool autoCommit = false)
        {
            publisher.Transaction.Value = (ICapTransaction)publisher.ServiceProvider.GetService(typeof(ICapTransaction));
            return publisher.Transaction.Value.Begin(unitOfWork.GetOrBeginTransaction(), autoCommit);
        }

        public static void Commit(this ICapTransaction capTransaction, IUnitOfWork unitOfWork)
        {
            unitOfWork.Commit();
            capTransaction.Flush();
        }
    }
```


注入我们的FreeSql
```
public void ConfigureServices(IServiceCollection services)
 {
    IConfigurationSection configurationSection = Configuration.GetSection($"ConnectionStrings:MySql");
    IFreeSql fsql = new FreeSqlBuilder()
           .UseConnectionString(DataType.MySql, configurationSection.Value);
           .UseNameConvert(NameConvertType.PascalCaseToUnderscoreWithLower)
           .UseAutoSyncStructure(true)
           .UseNoneCommandParameter(true)
           .UseMonitorCommand(cmd =>
           {
               Trace.WriteLine(cmd.CommandText + ";");
           }
           )
           .Build();


    services.AddSingleton(fsql);
    services.AddFreeRepository();
    services.AddScoped<UnitOfWorkManager>();
}
```

## 示例
```
    [HttpGet("~/freesql/unitofwork/{id}")]
    public DateTime UnitOfWorkManagerTransaction(int id, [FromServices] IBaseRepository<Book> repo)
    {
        DateTime now = DateTime.Now;
        using (IUnitOfWork uow = _unitOfWorkManager.Begin())
        {
            ICapTransaction trans = _unitOfWorkManager.Current.BeginTransaction(_capBus, false);
            repo.Insert(new Book()
            {
                Author = "luoyunchong",
                Summary = "2",
                Title = "122"
            });

            _capBus.Publish("freesql.time", now);
            trans.Commit(uow);
        }
        return now;
    }
    
    [NonAction]
    [CapSubscribe("freesql.time")]
    public void GetTime(DateTime time)
    {
        Console.WriteLine($"time:{time}");
    }
```

注意trans不需要using，freesql内部会释放资源。，也可using，但请更新到最新的freesql版本。
```
ICapTransaction trans = _unitOfWorkManager.Current.BeginTransaction(_capBus, false);
```

提交事务，也请调用扩展方法，否则事务无法正常。
```
trans.Commit(uow);
```
