### ISSUE TITLE
.net 5 单文件发布出错

### ISSUE THREAD

**Issue by windhuan** [dotnetcore/FreeSql#540]
.net 5 单文件发布出错

根据文档描述 Assembly.CodeBase 不支持在单文件下访问
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

异常信息:
System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at FreeSql.Internal.CommonUtils.<GetProperyCommentBySummary>g__LocalGetComment|46_0(Type localType, Int32 level)
   at FreeSql.Internal.CommonUtils.GetProperyCommentBySummary(Type type)
   at FreeSql.Internal.Utils.GetTableByEntity(Type entity, CommonUtils common)
   at FreeSql.Internal.CommonUtils.GetTableByEntity(Type entity)
   at FreeSql.Internal.CommonProvider.Select0Provider`2..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Internal.CommonProvider.Select1Provider`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.Curd.SqliteSelect`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.SqliteProvider`1.CreateSelectProvider[T1](Object dywhere)
   at FreeSql.Internal.CommonProvider.BaseDbProvider.Select[T1]()
   at FreeSqlGlobalExtensions.Queryable[T](IFreeSql freesql)
   at TMDrugM.Client.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at FreeSql.Internal.CommonUtils.<GetProperyCommentBySummary>g__LocalGetComment|46_0(Type localType, Int32 level)
   at FreeSql.Internal.CommonUtils.GetProperyCommentBySummary(Type type)
   at FreeSql.Internal.Utils.GetTableByEntity(Type entity, CommonUtils common)
   at FreeSql.Internal.CommonUtils.GetTableByEntity(Type entity)
   at FreeSql.Internal.CommonProvider.Select0Provider`2..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Internal.CommonProvider.Select1Provider`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.Curd.SqliteSelect`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.SqliteProvider`1.CreateSelectProvider[T1](Object dywhere)
   at FreeSql.Internal.CommonProvider.BaseDbProvider.Select[T1]()
   at FreeSqlGlobalExtensions.Queryable[T](IFreeSql freesql)

**Comment by 2881099** [comment]
也许 sqlite 不行

**Comment by windhuan** [comment]
System.Data.SQLite.Core 更新到1.0.113.2 之后的版本已经修复了单文件发布问题

**Comment by 2881099** [comment]
NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.

这个问题已解决，更新到【 v2.0.0-preview1123 】
