### ISSUE TITLE
Constructor on type 'System.Decimal' not found.

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/FreeSql#559]
经测试 用Dapper和EF插入是正常的，用FreeSql会报错
version 1.9.0.0
postgresql :  12
table:

CREATE TABLE "public"."T_LifterBasics" (
  "Id" uuid NOT NULL,
  "CreationTime" timestamp(6) NOT NULL,
  "IsDeleted" bool NOT NULL,
  "SerialNo" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "FakeNo" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "RecordTime" timestamp(6) NOT NULL,
  "LifterId" int4 NOT NULL,
  "MaxWeight" numeric(16,4) NOT NULL,
  "MaxFloor" int4,
  "MaxHeight" numeric(16,4) NOT NULL,
  "MaxSpeed" numeric(16,4) NOT NULL,
  "MaxTilt" numeric(16,4) NOT NULL,
  "MaxPeopleNumber" int4 NOT NULL,
  "LiftName" text COLLATE "pg_catalog"."default",
  "MinFloor" int4 NOT NULL,
  "MinHeight" numeric(16,4),
  "MaxWindSpeed" numeric(16,4),
  CONSTRAINT "PK_T_LifterBasics" PRIMARY KEY ("Id")
)
;

Data :   
new LifterBasic()
            {
                LifterId = 1,
                LiftName = "Test呀test!",
                MaxFloor = 30,
                MaxHeight = 90,
                MaxPeopleNumber = 13,
                MaxSpeed = 2,
                MaxTilt = 0.05M,
                MaxWeight = 1.3M,
                MaxWindSpeed = 10,
                MinFloor = -3,
                MinHeight = -9
            });

Constructor on type 'System.Decimal' not found.

   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at FreeSqlGlobalExtensions.CreateInstanceGetDefaultValue(Type that)
   at FreeSql.Internal.Utils.GetTableByEntity(Type entity, CommonUtils common)
   at FreeSql.Internal.CommonUtils.GetTableByEntity(Type entity)
   at FreeSql.Internal.CommonProvider.InsertProvider`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression)
   at FreeSql.PostgreSQL.Curd.PostgreSQLInsert`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression)
   at FreeSql.PostgreSQL.PostgreSQLProvider`1.Insert[T1]()
   at FreeSql.PostgreSQL.PostgreSQLProvider`1.Insert[T1](T1 source)
   at ARchGL.IOT.DataCenter.Consumer.DataCenterConsumer`2.<EventProcess>d__15.MoveNext() in D:\Projects\SPD\IOT\src\DataCenter\ARchGL.IOT.DataCenter.Consumer\DataCenterConsumer.cs:line 78

**Comment by 2881099** [comment]
升级到 2.0.0-preview 试试

**Comment by liugt34** [comment]
补充实体类
`    [Table("T_LifterBasics", Schema = "public")]
    public class LifterBasicBase : DeviceRecord
    {
        [Required]
        public virtual short LifterId { get; set; }

        public virtual string LiftName { get; set; }

        [Required]
        public virtual decimal? MaxWeight { get; set; }

        public virtual int? MaxFloor { get; set; }

        public virtual int? MinFloor { get; set; }

        [Required]
        public virtual decimal? MaxHeight { get; set; }

        public virtual decimal? MinHeight { get; set; }

        [Required]
        public virtual decimal? MaxSpeed { get; set; }

        [Required]
        public virtual decimal? MaxTilt { get; set; }

        public virtual decimal? MaxWindSpeed { get; set; }

        [Required]
        public virtual int? MaxPeopleNumber { get; set; }`

**Comment by 2881099** [comment]
我这边在当前版本中没有出现这个错误

升级尝试了吗，如果还有问题，请告诉我运行环境，我再去尝试。

**Comment by liugt34** [comment]
不敢升级呀 [尴尬]

**Comment by 2881099** [comment]
不要怕，freesql 版本跟不像 ef 那样不管兼容

**Comment by liugt34** [comment]
已经解决了，把Required特性去掉就正常了，(((φ(◎ロ◎;)φ)))

**Comment by 2881099** [comment]
```c#
var defv1 = typeof(decimal).CreateInstanceGetDefaultValue();
var defv2 = typeof(decimal?).CreateInstanceGetDefaultValue();
```

试试这个会不会报错。
