### ISSUE TITLE
为什么decimal类型小数点不能支持4位？

### ISSUE THREAD

**Issue by rjf1979** [dotnetcore/FreeSql#594]
decimal(18,4) 为什么不能更新数据库，报错消息： System.ArgumentException: Parameter value '698829924.67' is out of range.
希望能支持一下大于2位以上的小数，这是金融系统的需求

**Comment by 2881099** [comment]
怎么设的？实体类设置了长度吗，[Column(Persion = , Scale =

**Comment by rjf1979** [comment]
设定了，[Column(Persion = 18, Scale =4)] 但还是没用

**Comment by 2881099** [comment]
什么数据库

**Comment by rjf1979** [comment]
sql server

**Comment by rjf1979** [comment]
sql server 2012

**Comment by 2881099** [comment]
```c#
	public class _594
	{
		[Fact]
		public void Decimal()
		{
            var fsql = g.sqlserver;

            fsql.Delete<ts_decimal_18_4>().Where("1=1").ExecuteAffrows();
            var id = Guid.NewGuid();

            Assert.Equal(1, fsql.Insert(new ts_decimal_18_4 { id = id }).ExecuteAffrows());
            Assert.Equal(1, fsql.Update<ts_decimal_18_4>(id)
                .Set(a => a.price, 698829924.67m)
                .ExecuteAffrows());

            Assert.Equal(1, fsql.Update<ts_decimal_18_4>()
                .SetSource(new ts_decimal_18_4 { id = id, price = 698829924.67m })
                .ExecuteAffrows());
        }

        class ts_decimal_18_4
        {
            public Guid id { get; set; }
            [Column(Precision = 18, Scale = 4)]
            public decimal price { get; set; }
        }
    }
```

我写了测试没问题

**Comment by rjf1979** [comment]
我真实环境值是：698830024.6700

**Comment by rjf1979** [comment]
小数点后四位

**Comment by rjf1979** [comment]
2020-12-07 15:40:55.5643
Connection ID "17798304893816013199", Request ID "(null)": An unhandled exception was thrown by the application.
System.Exception: Parameter value '698829924.67' is out of range.
 ---> System.ArgumentException: Parameter value '698829924.67' is out of range.
   at Microsoft.Data.SqlClient.TdsParser.TDSExecuteRPCAddParameter(TdsParserStateObject stateObj, SqlParameter param, MetaType mt, Byte options)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.InsertProvider`1.RawExecuteAffrows()
   at FreeSql.Internal.CommonProvider.InsertProvider`1.SplitExecuteAffrows(Int32 valuesLimit, Int32 parameterLimit)
   at FreeSql.SqlServer.Curd.SqlServerInsert`1.ExecuteAffrows()
   at Asmkt.Client.Business.DomainServices.ClientAccountFlowService.Add(ClientAccount clientAccount, ClientAccountFlowType flowType, Int64 businessId, Decimal amount)
   at Asmkt.Client.Business.Api.Controllers.ClientAccountController.<>c__DisplayClass5_0.<OrderDeduct>b__0()
   at FreeSql.Internal.CommonProvider.AdoProvider.TransactionInternal(Nullable`1 isolationLevel, Action handler)
   at FreeSql.Internal.CommonProvider.AdoProvider.Transaction(Action handler)
   at FreeSql.Internal.CommonProvider.BaseDbProvider.Transaction(Action handler)
   at Asmkt.Client.Business.Api.Controllers.ClientAccountController.OrderDeduct(DeductBalanceOfOrderRequestModel model)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IGeekFan.AspNetCore.Knife4jUI.Knife4jUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync() 
 <ProcessRequestAsync>d__2.MoveNext => IISHttpContext.ReportApplicationError => Log.ApplicationError

**Comment by 2881099** [comment]
```c#
fsql.Delete<ts_decimal_18_4>().Where("1=1").ExecuteAffrows();
var id = Guid.NewGuid();

Assert.Equal(1, fsql.Insert(new ts_decimal_18_4 { id = id }).ExecuteAffrows());
Assert.Equal(1, fsql.Update<ts_decimal_18_4>(id)
    .Set(a => a.price, 698830024.6700m)
    .ExecuteAffrows());

Assert.Equal(1, fsql.Update<ts_decimal_18_4>()
    .SetSource(new ts_decimal_18_4 { id = id, price = 698830024.6700m })
    .ExecuteAffrows());

Assert.Equal(1, fsql.Update<ts_decimal_18_4>(id).NoneParameter()
    .Set(a => a.price, 698830024.6700m)
    .ExecuteAffrows());

Assert.Equal(1, fsql.Update<ts_decimal_18_4>().NoneParameter()
    .SetSource(new ts_decimal_18_4 { id = id, price = 698830024.6700m })
    .ExecuteAffrows());
```

```bash

线程15: DELETE FROM [ts_decimal_18_4] WHERE (1=1)

线程15: INSERT INTO [ts_decimal_18_4]([id], [price]) VALUES(@id_0, @price_0)

线程15: UPDATE [ts_decimal_18_4] SET [price] = @p_0 
WHERE ([id] = 'bf9420f1-3b96-476a-9160-cd69de69f7ad')

线程15: UPDATE [ts_decimal_18_4] SET [price] = @p_0 
WHERE ([id] = 'bf9420f1-3b96-476a-9160-cd69de69f7ad')

线程15: UPDATE [ts_decimal_18_4] SET [price] = 698830024.6700 
WHERE ([id] = 'bf9420f1-3b96-476a-9160-cd69de69f7ad')

线程15: UPDATE [ts_decimal_18_4] SET [price] = 698830024.6700 
WHERE ([id] = 'bf9420f1-3b96-476a-9160-cd69de69f7ad')
```

这是监控的 SQL

**Comment by 2881099** [comment]
没有报错

**Comment by rjf1979** [comment]
有点纳闷了，怎么会这样

**Comment by 2881099** [comment]
at Microsoft.Data.SqlClient.TdsParser.TDSExecuteRPCAddParameter(TdsParserStateObject stateObj, SqlParameter param, MetaType mt, Byte options)
at Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource1 completion, Int32 startRpc, Int32 startParam) at

看堆栈信息，错误发生在 Tds 上了，分布式事务服务？

试试用 fsql.Update\<ts_decimal_18_4\>().NoneParameter() 这种模式更新。

**Comment by rjf1979** [comment]
_freeSql.Transaction(() =>

**Comment by rjf1979** [comment]
我用的是同线程的事务操作

**Comment by rjf1979** [comment]
我找到问题了，有两个表里货币字段，之前是没加特性：[Column(Precision = 18, Scale = 4)]
默认[Column(Precision = 10, Scale = 2]，不支持，加了一个没处理第二个表的货币字段
建议货币类型的[Column(Precision = 18, Scale = 4)]，这样比较通吃点，防止货币长度不够，谢谢你了

**Comment by densen2014** [comment]
我使用的是 [JsonProperty, Column(DbType = "decimal(19,4)")]  , 用了很久了.  希望能帮到你
