### ISSUE TITLE
System.Exception: ObjectPool.Get 获取超时（10秒）。

### ISSUE THREAD

**Issue by gwhzh21** [dotnetcore/FreeSql#606]
版本 1.7.1
偶尔出现。
System.Exception: ObjectPool.Get 获取超时（10秒）。
 ---> System.TimeoutException: ObjectPool.Get 获取超时（10秒）。
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivate(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListPrivate(GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToList(Boolean includeNestedMembers)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.ToList(Boolean includeNestedMembers)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToOne()
   at FreeSql.Internal.CommonProvider.Select0Provider`2.First()

开了100个连接，数据库也没有异常，理论上不应该会有这种情况？

**Comment by 2881099** [comment]
有没有使用过 fsql.Ado.MasterPool.Get() 或 GetAsync() 方法。

其他：

原因一：UnitOfWork 使用未释放，请保证程序内使用 UnitOfWork 的地方会执行 Dispose

原因二：Max Pool Size 设置过小，程序访问量过高

监视 fsql.Ado.MasterPool.Statistics，它的值：Pool: 5/100, Get wait: 0, GetAsync await: 0

5 为可用连接数，值为0后开始排队
100 为当前最大连接数
Get await 为同步方法获取连接的排队数量（超过10秒就会报错）
GetAsync await 为异步方法获取连接的排队数量
监视 FreeSql.UnitOfWork.DebugBeingUsed 这个静态字典，存储正在使用事务的工作单元

**Comment by gwhzh21** [comment]
好的。我的max pool size是300。但是那个时候的访问不到50.不应该，我只能靠猜，把数据库的事务改成了Snapshot模式。继续观察。

**Comment by gwhzh21** [comment]
var topnapp = await _freeSql.Select<t_wx_component_set>().FirstAsync();
有一些地方是这样的写的。
t_wx_component_set mset = _freeSql.Select<t_wx_component_set>().First();
有一些地方是同步的。

**Comment by 2881099** [comment]
建议不要异步，同步方法交叉使用，并发的时候很容易线程死锁。

**Comment by gwhzh21** [comment]
一般是同一个方法里面用的同样的方式。不存在同一个方法使用不同的方式。

**Comment by 2881099** [comment]
那就按上面说的，检查其他几个列出来的地方
