### ISSUE TITLE
System.Data.OscarClient in ubuntu   Socket.IOControl handles windows-specific controls codes and is not supported

### ISSUE THREAD

**Issue by luoyunchong** [dotnetcore/FreeSql#656]
*FreeSql.Provider.ShenTong*神通使用的dll是这个*System.Data.OscarClient*。经测试，无法在linux下运行。

一直提示
```
    Socket.IOControl handles windows-specific controls codes and is not supported
```
通过源码引用。调试发现如下堆栈信息。

  at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable) in D:\code\github\FreeSql\FreeSql\Internal\ObjectPool\ObjectPool.cs:line 272
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout) in D:\code\github\FreeSql\FreeSql\Internal\ObjectPool\ObjectPool.cs:line 303
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms) in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\AdoProvider\AdoProvider.cs:line 811
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms) in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\AdoProvider\AdoProvider.cs:line 797
   at FreeSql.ShenTong.ShenTongCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects) in D:\code\github\FreeSql\Providers\FreeSql.Provider.ShenTong\ShenTongCodeFirst.cs:line 119
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects) in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\CodeFirstProvider.cs:line 108
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]() in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\CodeFirstProvider.cs:line 85
   at FreeSql.Internal.CommonProvider.Select0Provider`2..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere) in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select0Provider.cs:line 180
   at FreeSql.Internal.CommonProvider.Select1Provider`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere) in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select1Provider.cs:line 23
   at FreeSql.ShenTong.Curd.ShenTongSelect`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere) in D:\code\github\FreeSql\Providers\FreeSql.Provider.ShenTong\Curd\ShenTongSelect.cs:line 117
   at FreeSql.ShenTong.ShenTongProvider`1.CreateSelectProvider[T1](Object dywhere) in D:\code\github\FreeSql\Providers\FreeSql.Provider.ShenTong\ShenTongProvider.cs:line 12
   at FreeSql.Internal.CommonProvider.BaseDbProvider.Select[T1]() in D:\code\github\FreeSql\FreeSql\Internal\CommonProvider\BaseDbProvider.cs:line 16
   at FreeSqlService.DAL.BaseDAL`1.Query(Expression`1 where, Expression`1 orderby, PageInfo pageInfo) in D:\Users\Computer\Desktop\WebCore\FreeSqlService\DAL\BaseDAL.cs:line 182
   at WebCore.Controllers.HomeController.JsonDemoYhxx(Int32 page, Int32 limit) in D:\Users\Computer\Desktop\WebCore\WebCore\Controllers\HomeController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

   This exception was originally thrown at this call stack:
    System.Net.Sockets.SocketPal.WindowsIoctl(System.Net.Sockets.SafeSocketHandle, int, byte[], byte[], out int)
    System.Net.Sockets.Socket.IOControl(int, byte[], byte[])
    System.Data.OscarClient.OscarClosedState.Open(System.Data.OscarClient.OscarConnector)

    Socket.IOControl handles windows-specific controls codes and is not supported

类似的问题。
    https://github.com/statianzo/Fleck/pull/232

## 源码 System.Data.OscarClient 中的OscarClosedState.cs
[OscarClosedState.zip](https://github.com/dotnetcore/FreeSql/files/5846336/OscarClosedState.zip)

```csharp
     public override void Open(OscarConnector context)
        {
            //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
            //IL_0200: Expected O, but got Unknown
            //IL_0202: Unknown result type (might be due to invalid IL or missing references)
            //IL_020e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0218: Expected O, but got Unknown
            //IL_021a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0226: Unknown result type (might be due to invalid IL or missing references)
            //IL_0230: Expected O, but got Unknown
            //IL_0232: Unknown result type (might be due to invalid IL or missing references)
            //IL_023e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0248: Expected O, but got Unknown
            try
            {
                OscarEventLog.LogMethodEnter(LogLevel.Interface, CLASSNAME, "Open");
                IPAddress[] array = ResolveIPHost(context.Host);
                Socket socket = null;
                uint num = 0u;
                byte[] array2 = new byte[Marshal.SizeOf((object)num) * 3];
                if (context.enableKeepalive)
                {
                    BitConverter.GetBytes(1u).CopyTo(array2, 0);
                }
                else
                {
                    BitConverter.GetBytes(0u).CopyTo(array2, 0);
                }

                BitConverter.GetBytes(context.tcp_keepalive_time).CopyTo(array2, Marshal.SizeOf((object)num));
                BitConverter.GetBytes(context.tcp_keepalive_intvl).CopyTo(array2, Marshal.SizeOf((object)num) * 2);
                IPAddress[] array3 = array;
                foreach (IPAddress iPAddress in array3)
                {
                    OscarEventLog.LogMsg(OscarState.resman, "Log_ConnectingTo", LogLevel.Interface, iPAddress);
                    IPEndPoint iPEndPoint = new IPEndPoint(iPAddress, context.Port);
                    socket = new Socket(iPEndPoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
                    socket.IOControl(IOControlCode.KeepAliveValues, array2, null);
                    try
                    {
                        IAsyncResult asyncResult = socket.BeginConnect(iPEndPoint, null, null);
                        if (!asyncResult.AsyncWaitHandle.WaitOne(context.ConnectionTimeout * 1000, exitContext: true))
                        {
                            socket.Close();
                            throw new Exception(OscarState.resman.GetString("Exception_ConnectionTimeout"));
                        }

                        socket.EndConnect(asyncResult);
                    }
                    catch (Exception)
                    {
                        OscarEventLog.LogMsg(OscarState.resman, "Log_FailedConnection", LogLevel.Interface, iPAddress);
                        socket.Close();
                        continue;
                    }

                    break;
                }

                if (socket == null || !socket.Connected)
                {
                    throw new Exception(string.Format(OscarState.resman.GetString("Exception_FailedConnection"), context.Host));
                }

                Stream stream = new NetworkStream(socket, ownsSocket: true);
                if (context.SSL || context.SslMode == SslMode.Require || context.SslMode == SslMode.Prefer)
                {
                    OscarUtil.WriteInt32(stream, 8);
                    OscarUtil.WriteInt32(stream, 80877103);
                    char c = (char)stream.ReadByte();
                    if (c == 'S')
                    {
                        stream = (Stream)new SslClientStream(stream, context.Host, true, (SecurityProtocolType)(-1073741824));
                        ((SslClientStream)stream).set_ClientCertSelectionDelegate((CertificateSelectionCallback)(object)new CertificateSelectionCallback(context.DefaultCertificateSelectionCallback));
                        ((SslClientStream)stream).set_ServerCertValidationDelegate((CertificateValidationCallback)(object)new CertificateValidationCallback(context.DefaultCertificateValidationCallback));
                        ((SslClientStream)stream).set_PrivateKeyCertSelectionDelegate((PrivateKeySelectionCallback)(object)new PrivateKeySelectionCallback(context.DefaultPrivateKeySelectionCallback));
                    }
                    else if (context.SslMode == SslMode.Require)
                    {
                        throw new InvalidOperationException(OscarState.resman.GetString("Exception_Ssl_RequestError"));
                    }
                }

                context.Stream = new BufferedStream(stream);
                context.Socket = socket;
                OscarEventLog.LogMsg(OscarState.resman, "Log_ConnectedTo", LogLevel.Interface, context.Host, context.Port);
                OscarState.ChangeState(context, OscarConnectedState.Instance);
            }
            catch (ThreadAbortException)
            {
                throw;
            }
            catch (Exception ex3)
            {
                throw new OscarException(ex3.Message, ex3);
            }
        }
```

内部的确有

```csharp
 socket = new Socket(iPEndPoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
                    socket.IOControl(IOControlCode.KeepAliveValues, array2, null);
```

参考
[https://www.nuget.org/packages/ShenTong.EntityFrameworkCore.Oscar/](https://www.nuget.org/packages/ShenTong.EntityFrameworkCore.Oscar/)底层引用的dll是 [https://www.nuget.org/packages/Oscar.Data.SqlClient/](https://www.nuget.org/packages/Oscar.Data.SqlClient/)

**Comment by 2881099** [comment]
安装前添加源：https://www.myget.org/F/ncc/api/v3/index.json
