### ISSUE TITLE
分页出问题了，看看怎么回事？

### ISSUE THREAD

**Issue by rjf1979** [dotnetcore/FreeSql#666]
2021-01-25 11:13:06.5179 合计数据异常  
 System.Exception: ORDER BY 子句中的列 "Data_SupplyCostSettlementOrderByDay.Date" 无效，因为该列没有包含在聚合函数或 GROUP BY 子句中。
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): ORDER BY 子句中的列 "Data_SupplyCostSettlementOrderByDay.Date" 无效，因为该列没有包含在聚合函数或 GROUP BY 子句中。
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
ClientConnectionId:2209bbf6-3f72-4d8e-b68e-fe61f6d3c299
Error Number:8127,State:1,Class:16
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAsync[TTuple](String field, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalSumAsync(Expression exp, CancellationToken cancellationToken)
   at Asmkt.Report.Web.Areas.BusinessSettle.Controllers.SupplyCostSettlementOrderController.ListByDay(IFormCollection form) 
 ExecutionContext.RunInternal => AsyncStateMachineBox`1.ExecutionContextCallback => <ListByDay>d__13.MoveNext

**Comment by rjf1979** [comment]
找到问题了，先分页操作后，再拿条件进行做合计统计，会发生问题，默认记录到了orderby，但合计统计时脚本里带了orderby
