### ISSUE TITLE
UseConnectionFactory方式连接mysql多线程时连不上数据库

### ISSUE THREAD

**Issue by lyg1949** [dotnetcore/FreeSql#736]
使用的freesql版本 `1.7.1`
mysql版本 `5.7`
netcore版本`2.2`
连接字符串：`Data Source=127.0.0.1;Port=3306;User ID=root;Password=test;Initial Catalog=demo;Charset=utf8;SslMode=none`

线程的限制
```
ThreadPool.SetMaxThreads(5, 5);
ThreadPool.SetMinThreads(5, 1);
```
如果程序启动后就开始多线程访问数据库，会报错`Unable to connect to any of the specified MySQL hosts`,这时完全不能读写数据库。

如果程序启动后先单线程处理，之后再多线程访问数据库，除`Unable to connect to any of the specified MySQL hosts`之外
还有：
```
System.Exception: Unable to connect to any of the specified MySQL hosts. ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> MySql.Data.MySqlClient.MySqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at FreeSql.Internal.CommonProvider.DbConnectionPool.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.InsertProvider`1.RawExecuteAffrows()
   at FreeSql.Internal.CommonProvider.InsertProvider`1.SplitExecuteAffrows(Int32 valuesLimit, Int32 parameterLimit)
   at FreeSql.MySql.Curd.MySqlInsert`1.ExecuteAffrows()
```
这种情况下会有一些线程读写数据库成功。

能知道什么原因吗？

谢谢！

**Comment by 2881099** [comment]
远程访问 mysql 吗？

UseConnectionFactory 要自己控制好连接池释放，是会比较麻烦

**Comment by lyg1949** [comment]
程序跑在docker里面，能问一下自己怎么控制连接池释放？我看说明不是用完会自己关闭吗？

**Comment by lyg1949** [comment]
> 远程访问 mysql 吗？
> 
> UseConnectionFactory 要自己控制好连接池释放，是会比较麻烦

程序跑在docker里面，能问一下自己怎么控制连接池释放？我看说明不是用完会自己关闭吗？

**Comment by 2881099** [comment]
MySqlConnection 释放跟 SqlConnection 有点区别

除了 conn.Close() 以外，还需要进行 MySqlConnection.ClearPool(conn)

**Comment by 2881099** [comment]
Unable to connect to any of the specified MySQL hosts

这个错误看上去不像连接池问题产生的。你试试直接用 new MySqlConnection Open 纯 ADO.NET 的方式测试，看看会不会有这种情况。

**Comment by lyg1949** [comment]
原因可能是同时多个线程（多于cpu核）访问数据库（同时cpu繁忙？？？）

经测试线程数小于cpu核时不会出现这个问题。

挺奇怪的！
