### ISSUE TITLE
如果实体设置了 [Column(RereadSql)] 时使用树查询 AsTreeCte().ToTreeListAsync() 生成的语句缺失别名导致执行失败

### ISSUE THREAD

**Issue by VicBilibily** [dotnetcore/FreeSql#964]
#### 问题描述及重现步骤：
```csharp
    [Table(Name = "F_PlanCostItem", DisableSyncStructure = true)]
    public partial class FPlanCostItemDM
    {
        #region 数据映射定义
        [Column(IsPrimary = true, IsIdentity = true)]
        public int ID { get; set; }
        public int BillID { get; set; }
        public int GoodsID { get; set; }
        ......
        public int ParentID { get; set; } = 0;
        ......
        [Column(DbType = "timestamp", CanInsert = false, CanUpdate = false, RereadSql = "CONVERT(BIGINT,{0})")]
        public long YthTimestamp { get; set; }
        #endregion

        #region 数据导航属性
        [Navigate(nameof(ParentID))]
        public virtual FPlanCostItemDM Parent { get; set; }
        [Navigate(nameof(ParentID))]
        public virtual List<FPlanCostItemDM> Childs { get; set; }
        #endregion
    }

var trees = await erpUow.Orm.Select<FPlanCostItemDM>().Where(v => v.ID == newErpItemCost.ID).AsTreeCte().ToTreeListAsync();
````

#### 生成语句
``` sql

WITH [as_tree_cte]
as
(
SELECT 0 as cte_level, a.[ID], a.[BillID], a.[GoodsID],     ......    a.[ParentID],     ......    CONVERT(BIGINT,a.[YthTimestamp]) 
FROM [F_PlanCostItem] a 
WHERE (a.[ID] = 608876)

union all

SELECT wct1.cte_level + 1 as cte_level, wct2.[ID], wct2.[BillID], wct2.[GoodsID],     ......    wct2.[ParentID],    ......    CONVERT(BIGINT,wct2.[YthTimestamp]) 
FROM [as_tree_cte] wct1 
INNER JOIN [F_PlanCostItem] wct2 ON wct2.[ParentID] = wct1.[ID]
)
SELECT a.[ID], a.[BillID], a.[GoodsID],    ......    a.[ParentID],    ......    CONVERT(BIGINT,a.[YthTimestamp]) 
FROM [as_tree_cte] a
````

#### 错误信息
```
System.Exception: 没有为 'as_tree_cte' 的列 75 指定任何列名称。
 ---> System.Data.SqlClient.SqlException (0x80131904): 没有为 'as_tree_cte' 的列 75 指定任何列名称。
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
ClientConnectionId:053c1d3e-1ca4-4ac1-8ae1-78cf16e17180
Error Number:8155,State:2,Class:16
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivateAsync(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData, CancellationToken cancellationToken)
```

#### 数据库的具体版本
```
SQL SERVER 2008
```

#### 安装的包
```
<PackageReference Include="FreeSql.Provider.SqlServerForSystem" Version="2.6.100" />
```

#### .net framework/. net core？ 及具体版本
```
net6
```

**Comment by luoyunchong** [comment]
`RereadSql = "CONVERT(BIGINT,{0}) as YthTimestamp"`试了吗

**Comment by VicBilibily** [comment]
试过了 会有其他问题 直接Select会两个别名报错

> `RereadSql = "CONVERT(BIGINT,{0}) as YthTimestamp"`试了吗

**Comment by luoyunchong** [comment]
`RereadSql = "CONVERT(BIGINT,{0}) YthTimestamp"`这样写。测了没问题。

```csharp
            var trees2 = await _fsql.Select<FPlanCostItemDM>().ToListAsync();
            var trees = await _fsql.Select<FPlanCostItemDM>().AsTreeCte().ToTreeListAsync();
```

**Comment by 2881099** [comment]
@VicBilibily @luoyunchong 这是一个 bug，已经处理了
