### ISSUE TITLE
[JsonMap]字段在服务运行一段时间后查询时找不到列

### ISSUE THREAD

**Issue by ycqhg** [dotnetcore/FreeSql#997]
#### 问题描述及重现步骤：
[JsonMap]字段在服务运行一段时间后查询时找不到列，重启服务正常。服务部署在win server 2012 r2 IIS 8.5

异常信息：
System.ArgumentException: SPPayType 找不到列 PayTypes
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc)
   at FreeSql.Internal.CommonExpression.ExpressionSelectColumn_MemberAccess(List`1 _tables, List`1 _selectColumnMap, SelectTableInfoType tbtype, Expression exp, Boolean isQuoteName, BaseDiyMemberExpression diymemexp)
   at FreeSql.Internal.CommonExpression.ReadAnonymousField(List`1 _tables, StringBuilder field, ReadAnonymousTypeInfo parent, Int32& index, Expression exp, Select0Provider select, BaseDiyMemberExpression diymemexp, List`1 whereGlobalFilter, List`1 findIncludeMany, Boolean isAllDtoMap)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.GetExpressionField(Expression newexp, FieldAliasOptions fieldAlias)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalToListAsync[TReturn](Expression select, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.ToListAsync[TReturn](Expression`1 select, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.ToOneAsync[TReturn](Expression`1 select, CancellationToken cancellationToken)

字段定义：
    [Table(Name = "StationPilePayType")]
	public class StationPilePayType : EntityBase
    {

		/// <summary>
		/// 支付方式
		/// </summary>
		[JsonMap]
        public SPPayType PayTypes { get; set; }
    }

	public class SPPayType
    {
		/// <summary>
		/// 支付方式
		/// </summary>
        public List<PayType> PayTypes { get; set; }
    }

DB查询方式：
var payTypes = await _payTypeRepository
                .Where(d => d.ObjId == stationWait.StationId && d.ObjType == PriceObjType.Station)
                .ToOneAsync(d => d.PayTypes);

#### 数据库的具体版本
```
SQL Server2016 Web
```

#### 安装的包
```
FreeSql   2.5.200
FreeSql.Extensions.JsonMap   2.5.200
FreeSql.Provider.SqlServer   2.5.200
FreeSql.Repository   2.5.200
```

#### .net framework/. net core？ 及具体版本
```
.net core 3.1
```

**Comment by luoyunchong** [comment]
fql的定义不是单例。正常fsql单例的情况下。`  fsql.UseJsonMap();`只需要在初始化时调用 一次即可。当没有调用 此方法时，-会出现你说的这个错。

**Comment by ycqhg** [comment]
> fql的定义不是单例。正常fsql单例的情况下。` fsql.UseJsonMap();`只需要在初始化时调用 一次即可。当没有调用 此方法时，-会出现你说的这个错。

我试试从IdleBus<IFreeSql> 里Get时加上fsql.UseJsonMap();
